export type ActorType = "human" | "agent" | "system" | "swarm";

export type AuditActionType =
  | "COMMAND_PREVIEWED"
  | "COMMAND_SIMULATED"
  | "COMMAND_EXECUTED"
  | "COMMAND_BLOCKED"
  | "POLICY_CHECKED"
  | "ASSET_STATE_CHANGED"
  | "TASK_ASSIGNED"
  | "TASK_FAILED"
  | "ROLLBACK_STARTED"
  | "ROLLBACK_COMPLETED"
  | "TELEMETRY_UPDATED"
  | "AI_RECOMMENDATION_GENERATED"
  | "AUDIT_EXPORTED"
  | "APPROVAL_REQUIRED"
  | "OVERRIDE_REQUESTED"
  | "OVERRIDE_APPROVED"
  | "OVERRIDE_REJECTED"
  | "ZTA_POSTURE_UPDATED"
  | "POLICY_VIOLATION_DETECTED"
  | "APPROVAL_REQUESTED"
  | "APPROVAL_GRANTED"
  | "APPROVAL_CHANGES_REQUESTED"
  | "APPROVAL_ESCALATED"
  | "OPERATOR_JOINED"
  | "OPERATOR_LEFT"
  | "DECISION_NOTE_ADDED"
  | "INSIGHT_FEEDBACK_SUBMITTED"
  | "INSIGHT_EXPLANATION_VIEWED"
  | "AI_SYSTEM_REGISTERED"
  | "AI_RISK_ASSESSED"
  | "GOVERNANCE_REVIEW_REQUESTED"
  | "GOVERNANCE_REVIEW_APPROVED"
  | "GOVERNANCE_REVIEW_REJECTED"
  | "CONTROL_MAPPING_UPDATED"
  | "GOVERNANCE_EVIDENCE_EXPORTED"
  | "RED_TEAM_SCENARIO_STARTED"
  | "RED_TEAM_SCENARIO_COMPLETED"
  | "CHAOS_DRILL_STARTED"
  | "CHAOS_DRILL_COMPLETED"
  | "FAULT_INJECTED"
  | "SAFETY_ASSERTION_FAILED"
  | "DRILL_REPORT_EXPORTED"
  | "REMEDIATION_TASK_CREATED"
  | "EXECUTIVE_REPORT_GENERATED"
  | "PORTFOLIO_RISK_RECALCULATED"
  | "EXECUTIVE_RECOMMENDATION_GENERATED"
  | "BOARD_REPORT_EXPORTED"
  | "DECISION_CARD_CREATED"
  | "CAPABILITY_REGISTERED"
  | "CAPABILITY_TESTED"
  | "CAPABILITY_APPROVED"
  | "CAPABILITY_RESTRICTED"
  | "CAPABILITY_DEPRECATED"
  | "CAPABILITY_RETIRED"
  | "CAPABILITY_PERMISSION_CHANGED"
  | "CAPABILITY_EXECUTED"
  | "RUNBOOK_CREATED"
  | "RUNBOOK_VALIDATED"
  | "RUNBOOK_APPROVED"
  | "RUNBOOK_SIMULATED"
  | "RUNBOOK_EXECUTION_STARTED"
  | "RUNBOOK_STEP_COMPLETED"
  | "RUNBOOK_EXECUTION_FAILED"
  | "RUNBOOK_ROLLBACK_TRIGGERED"
  | "RUNBOOK_EXECUTION_SUCCEEDED"
  | "REMEDIATION_VERIFIED"
  | "TENANT_CREATED"
  | "TENANT_UPDATED"
  | "TENANT_SUSPENDED"
  | "TENANT_ARCHIVED"
  | "TENANT_USER_ADDED"
  | "TENANT_POLICY_UPDATED"
  | "TENANT_QUOTA_UPDATED"
  | "TENANT_ISOLATION_CHECKED"
  | "TENANT_REPORT_EXPORTED"
  | "HOCHSTER_REQUEST_RECEIVED"
  | "HOCHSTER_INSTANCE_ASSIGNED"
  | "HOCHSTER_ANALYSIS_STARTED"
  | "HOCHSTER_TOOL_EXECUTED"
  | "HOCHSTER_ROOT_CAUSE_IDENTIFIED"
  | "HOCHSTER_PATCH_GENERATED"
  | "HOCHSTER_PATCH_VALIDATED"
  | "HOCHSTER_TESTS_PASSED"
  | "HOCHSTER_TESTS_FAILED"
  | "HOCHSTER_SECURITY_WARNING"
  | "HOCHSTER_SOLUTION_GENERATED"
  | "HOCHSTER_CALLBACK_SENT"
  | "HOCHSTER_REQUEST_CANCELLED"
  | "HOCHSTER_SOLVER_MESH_STARTED"
  | "HOCHSTER_CANDIDATE_GENERATED"
  | "HOCHSTER_CANDIDATE_RANKED"
  | "HOCHSTER_SOLUTION_MEMORY_WRITTEN"
  | "HOCHSTER_MEMORY_REUSED"
  | "HOCHSTER_PR_REQUESTED"
  | "HOCHSTER_PR_CREATED"
  | "HOCHSTER_PR_BLOCKED"
  | "HOCHSTER_CALLBACK_DELIVERED"
  | "HOCHSTER_SECURITY_TEST_STARTED"
  | "HOCHSTER_SECURITY_TEST_COMPLETED"
  | "HOCHSTER_CERTIFICATION_REPORT_GENERATED"
  | "HOCHSTER_CERTIFICATION_PASSED"
  | "HOCHSTER_CERTIFICATION_FAILED"
  | "HOCHSTER_SBOM_GENERATED"
  | "HOCHSTER_PROVENANCE_ATTESTED"
  | "HOCHSTER_ARTIFACT_SIGNED"
  | "HOCHSTER_RELEASE_BLOCKED"
  | "HOCHSTER_ROLLOUT_RING_ADVANCED"
  | "HOCHSTER_ROLLOUT_RING_ROLLED_BACK"
  | "HOCHSTER_TENANT_ENABLED"
  | "HOCHSTER_TENANT_DISABLED"
  | "HOCHSTER_SLO_BREACH_DETECTED"
  | "HOCHSTER_MARKETPLACE_LISTING_CREATED"
  | "HOCHSTER_MARKETPLACE_LISTING_UPDATED"
  | "HOCHSTER_USAGE_QUOTA_UPDATED"
  | "HOCHSTER_VERSION_DEPRECATED"
  | "COMPLIANCE_CONTROL_MAPPED"
  | "COMPLIANCE_EVIDENCE_COLLECTED"
  | "COMPLIANCE_EVIDENCE_VALIDATED"
  | "COMPLIANCE_EVIDENCE_MARKED_STALE"
  | "COMPLIANCE_REPORT_EXPORTED"
  | "COMPLIANCE_ATTESTATION_REQUESTED"
  | "COMPLIANCE_ATTESTATION_COMPLETED"
  | "CUSTOMER_ONBOARDING_STARTED"
  | "CUSTOMER_ONBOARDING_TASK_COMPLETED"
  | "CUSTOMER_RISK_RECALCULATED"
  | "CUSTOMER_CHECKIN_SCHEDULED"
  | "CUSTOMER_REPORT_EXPORTED"
  | "REVENUE_PARTNER_REGISTERED"
  | "REVENUE_PARTNER_CERTIFIED"
  | "REVENUE_PRICING_PLAN_UPDATED"
  | "REVENUE_FORECAST_UPDATED"
  | "REVENUE_STRATEGIC_PRIORITY_UPDATED";

export type TargetType =
  | "asset"
  | "swarm"
  | "task"
  | "policy"
  | "command"
  | "system";

export type AuditResult =
  | "success"
  | "failed"
  | "blocked"
  | "warning"
  | "pending";

export type AuditSeverity =
  | "info"
  | "low"
  | "medium"
  | "high"
  | "critical";

export type ProvenanceSource =
  | "observed"
  | "inferred"
  | "predicted"
  | "manual"
  | "synthetic";

export type PolicyResult =
  | "passed"
  | "failed"
  | "not_required";

export type RollbackStatus =
  | "not_started"
  | "started"
  | "completed"
  | "failed";

export type AuditEvent = {
  event_id: string;
  correlation_id: string;
  timestamp: string;
  actor: {
    id: string;
    name: string;
    type: ActorType;
    role?: string;
  };
  action: {
    type: AuditActionType;
    summary: string;
    command_text?: string;
  };
  target: {
    type: TargetType;
    id: string;
    name?: string;
  };
  result: AuditResult;
  severity: AuditSeverity;
  provenance: {
    source: ProvenanceSource;
    confidence?: number;
    evidence_refs: string[];
  };
  policy: {
    required: boolean;
    result: PolicyResult;
    policy_ids?: string[];
    explanation?: string;
  };
  rollback?: {
    available: boolean;
    rollback_id?: string;
    status?: RollbackStatus;
  };
  metadata?: Record<string, unknown>;
};
