import type { AuditReport } from "./auditReportTypes";

export function auditReportToMarkdown(report: AuditReport): string {
  let md = `# Swarm Console Audit Report\n\n`;
  md += `**Report ID:** \`${report.report_id}\`  \n`;
  md += `**Generated At:** ${report.generated_at}  \n`;
  md += `**Generated By:** ${report.generated_by.name} (${report.generated_by.role ?? "Operator"})  \n`;
  md += `**Environment:** \`${report.environment}\`  \n`;
  md += `**Total Events:** ${report.event_count}  \n\n`;

  md += `## Integrity Scorecard\n\n`;
  md += `| Check Metric | Value | Status |\n`;
  md += `| --- | --- | --- |\n`;
  md += `| Valid Events | ${report.integrity.valid_event_count} | ${report.integrity.invalid_event_count === 0 ? "✅ Passed" : "⚠️ Warning"} |\n`;
  md += `| Invalid Events | ${report.integrity.invalid_event_count} | ${report.integrity.invalid_event_count === 0 ? "✅ Passed" : "❌ FAILED"} |\n`;
  md += `| Missing Policy Context | ${report.integrity.missing_policy_count} | ${report.integrity.missing_policy_count === 0 ? "✅ Passed" : "⚠️ Warning"} |\n`;
  md += `| Missing Evidence Refs | ${report.integrity.missing_evidence_count} | ${report.integrity.missing_evidence_count === 0 ? "✅ Passed" : "⚠️ Warning"} |\n`;
  md += `| Missing Confidence Values | ${report.integrity.missing_confidence_count} | ${report.integrity.missing_confidence_count === 0 ? "✅ Passed" : "⚠️ Warning"} |\n\n`;

  md += `## Applied Filters\n\n`;
  md += `\`\`\`json\n${JSON.stringify(report.filters, null, 2)}\n\`\`\`\n\n`;

  md += `## Event Summary Timeline\n\n`;
  md += `| Time | Action | Target | Actor | Result |\n`;
  md += `| --- | --- | --- | --- | --- |\n`;
  for (const event of report.events) {
    md += `| ${event.timestamp} | \`${event.action.type}\` | ${event.target.type}:${event.target.id} | ${event.actor.name} | **${event.result.toUpperCase()}** |\n`;
  }

  return md;
}
