import json
import hashlib
import io
import zipfile
import os
from datetime import datetime
from pathlib import Path

def get_ato_evidence_package() -> dict:
    from backend.ledger_manager import get_handoff_status
    handoff_status = get_handoff_status()
    
    # 1. NIST SP 800-53 Control-to-Evidence Matrix
    control_matrix = [
        {
            "control_id": "CM-2",
            "control_name": "Baseline Configuration",
            "evidence_item": "sbom.spdx.json & provenance.intoto.jsonl",
            "description": "Software Bill of Materials and provenance records generated by the build pipeline.",
            "status": "COMPLIANT"
        },
        {
            "control_id": "AU-2 / AU-12",
            "control_name": "Audit Events & Records",
            "evidence_item": "swarm_ledger.db",
            "description": "Immutable, recursively hashed cryptographic operator action ledger of all high-impact events.",
            "status": "COMPLIANT"
        },
        {
            "control_id": "CP-10",
            "control_name": "System Recovery",
            "evidence_item": "migration_recovery_dashboard",
            "description": "Rclone storage recovery strategies and guarded execution plans.",
            "status": "COMPLIANT"
        },
        {
            "control_id": "SC-7",
            "control_name": "Boundary Protection",
            "evidence_item": "exclusion_guard.py",
            "description": "Storage protection rules preventing model weight and token leakage during sync operations.",
            "status": "COMPLIANT"
        },
        {
            "control_id": "RA-3",
            "control_name": "Risk Assessment",
            "evidence_item": "model_health_monitor.py",
            "description": "Ollama local model availability and latency probe metrics.",
            "status": "COMPLIANT"
        },
        {
            "control_id": "SA-11",
            "control_name": "Developer Security Testing",
            "evidence_item": "run-ci-pipeline.py",
            "description": "Execution of 540 automated unit, contract, and UI-readiness QA tests.",
            "status": "COMPLIANT"
        }
    ]

    # 2. Residual Risk Register
    residual_risk_register = [
        {
            "risk_id": "RISK-001",
            "title": "Local Model Latency Spikes",
            "likelihood": "Medium",
            "impact": "Low",
            "mitigation": "Model Router Fallback automatically shifts traffic if Ollama server latency exceeds 8000ms.",
            "status": "MITIGATED"
        },
        {
            "risk_id": "RISK-002",
            "title": "Waived Cosign Code Signing",
            "likelihood": "Low",
            "impact": "Medium",
            "mitigation": "Local developer builds allow signature bypasses under audited manual operator override controls.",
            "status": "ACCEPTED_LOCAL_DEV"
        }
    ]

    # 3. Plan of Action and Milestones (POA&M)
    poam_register = [
        {
            "poam_id": "POAM-001",
            "title": "Enforce Strict Cosign Signature Verification",
            "scheduled_completion": "2026-09-30",
            "mitigation_strategy": "Bind local environment to external PKI or secure keystore for production code verification.",
            "status": "OPEN"
        },
        {
            "poam_id": "POAM-002",
            "title": "Dirty Git Tree Verification Hardening",
            "scheduled_completion": "2026-08-15",
            "mitigation_strategy": "Transition override permissions to hardware-bound MFA tokens to log override actor identities.",
            "status": "IN_PROGRESS"
        }
    ]

    # 4. Authorizing Official (AO) Review Checklist
    ao_checklist = [
        {
            "check_id": "AO-CHECK-01",
            "description": "Verify cryptographic integrity of the operator action ledger database.",
            "status": "PENDING_AO_REVIEW"
        },
        {
            "check_id": "AO-CHECK-02",
            "description": "Confirm system preflight scorecard matches or exceeds the 80% passing criteria.",
            "status": "PENDING_AO_REVIEW"
        },
        {
            "check_id": "AO-CHECK-03",
            "description": "Confirm model router probe response latencies stay below warning limits.",
            "status": "PENDING_AO_REVIEW"
        },
        {
            "check_id": "AO-CHECK-04",
            "description": "Confirm all 540 automated QA and compliance tests pass successfully.",
            "status": "PENDING_AO_REVIEW"
        }
    ]

    return {
        "statement": "ATO-SUPPORTING EVIDENCE PACKAGE: READY FOR REVIEW",
        "status_notice": "The system has ATO-supporting evidence prepared for review. Actual ATO has not been granted. No authorization claim is being made.",
        "generated_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "handoff_status": handoff_status,
        "control_matrix": control_matrix,
        "residual_risks": residual_risk_register,
        "poam": poam_register,
        "ao_checklist": ao_checklist
    }

def create_ato_evidence_zip() -> bytes:
    from backend.ledger_manager import create_handoff_packet
    package_data = get_ato_evidence_package()
    
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        # Save RMF package metadata
        zip_file.writestr("rmf_evidence_package.json", json.dumps(package_data, indent=2))
        
        # Include original handoff ZIP content (extract and re-write to maintain flat zip structure)
        handoff_bytes = create_handoff_packet()
        handoff_buffer = io.BytesIO(handoff_bytes)
        with zipfile.ZipFile(handoff_buffer, "r") as handoff_zip:
            for name in handoff_zip.namelist():
                zip_file.writestr(f"handoff/{name}", handoff_zip.read(name))
                
        # Generate complete manifest.sha256 matching everything in the package
        manifest_lines = []
        for name in zip_file.namelist():
            content = zip_file.read(name)
            h = hashlib.sha256(content).hexdigest()
            manifest_lines.append(f"{h}  {name}\n")
            
        zip_file.writestr("manifest.sha256", "".join(manifest_lines))
        
    return zip_buffer.getvalue()
