import type { CapabilityRecord } from "./capabilityTypes";

export const initialCapabilities: CapabilityRecord[] = [
  {
    capability_id: "threat-intel-analyst",
    name: "Threat Intel Analyst Agent",
    kind: "agent",
    version: "v1.4.2",
    owner: "SecOps Team",
    status: "testing",
    risk: "high",
    description: "Autonomously scans feeds, crawls OSINT databases, correlates IOCs, and flags emergent attack vectors.",
    tags: ["security", "threat-intel", "monitoring"],
    permissions: {
      filesystem: false,
      network: true,
      email: false,
      calendar: false,
      browser: true,
      shell: false,
      secrets: true,
      external_write: false,
    },
    guardrails: {
      requires_human_approval: true,
      allowed_environments: ["DEV", "STAGING"],
      blocked_actions: ["exec_shell", "delete_logs"],
      max_autonomy_level: "execute_with_approval",
    },
    lifecycle: {
      created_at: "2026-05-15T09:00:00Z",
      updated_at: "2026-06-10T14:30:00Z",
    },
    telemetry: {
      executions_30d: 1240,
      failure_rate_30d: 0.02,
      avg_latency_ms: 320,
      last_used_at: "2026-06-24T10:15:00Z",
    },
  },
  {
    capability_id: "email-triage-skill",
    name: "Email Triage Skill",
    kind: "skill",
    version: "v2.1.0",
    owner: "Comms Team",
    status: "approved",
    risk: "low",
    description: "Analyzes incoming email bodies, tags priorities, routes to specific department channels, and drafts templates.",
    tags: ["comms", "nlp", "triage"],
    permissions: {
      filesystem: false,
      network: true,
      email: true,
      calendar: false,
      browser: false,
      shell: false,
      secrets: false,
      external_write: true,
    },
    guardrails: {
      requires_human_approval: false,
      allowed_environments: ["LOCAL", "DEV", "STAGING", "PROD"],
      blocked_actions: ["send_unreviewed_email"],
      max_autonomy_level: "execute",
    },
    lifecycle: {
      created_at: "2026-04-10T08:00:00Z",
      approved_at: "2026-04-12T11:00:00Z",
      updated_at: "2026-06-01T09:20:00Z",
    },
    telemetry: {
      executions_30d: 3600,
      failure_rate_30d: 0.005,
      avg_latency_ms: 120,
      last_used_at: "2026-06-24T11:45:00Z",
    },
  },
  {
    capability_id: "k8s-remediation-tool",
    name: "K8s Remediation Tool",
    kind: "tool",
    version: "v1.8.3",
    owner: "Platform Team",
    status: "testing",
    risk: "high",
    description: "Integrates with kubectl to restart crashed pods, prune namespaces, and scale active replica sets.",
    tags: ["kubernetes", "devops", "remediation"],
    permissions: {
      filesystem: true,
      network: true,
      email: false,
      calendar: false,
      browser: false,
      shell: true,
      secrets: true,
      external_write: true,
    },
    guardrails: {
      requires_human_approval: true,
      allowed_environments: ["STAGING"],
      blocked_actions: ["delete_namespace_kube_system"],
      max_autonomy_level: "execute_with_approval",
    },
    lifecycle: {
      created_at: "2026-06-05T10:00:00Z",
      updated_at: "2026-06-20T16:15:00Z",
    },
    telemetry: {
      executions_30d: 845,
      failure_rate_30d: 0.04,
      avg_latency_ms: 950,
      last_used_at: "2026-06-24T09:22:00Z",
    },
  },
  {
    capability_id: "data-enrichment-connector",
    name: "Data Enrichment Connector",
    kind: "connector",
    version: "v1.0.7",
    owner: "Data Team",
    status: "approved",
    risk: "medium",
    description: "Syncs customer demographic metadata from external CRM tables to internal pipeline datasets.",
    tags: ["data", "etl", "crm"],
    permissions: {
      filesystem: false,
      network: true,
      email: false,
      calendar: false,
      browser: false,
      shell: false,
      secrets: true,
      external_write: true,
    },
    guardrails: {
      requires_human_approval: false,
      allowed_environments: ["DEV", "STAGING", "PROD"],
      blocked_actions: [],
      max_autonomy_level: "recommend",
    },
    lifecycle: {
      created_at: "2026-03-20T14:00:00Z",
      approved_at: "2026-03-22T09:00:00Z",
      updated_at: "2026-05-18T10:00:00Z",
    },
    telemetry: {
      executions_30d: 2100,
      failure_rate_30d: 0.015,
      avg_latency_ms: 450,
      last_used_at: "2026-06-24T11:08:00Z",
    },
  },
  {
    capability_id: "user-behavior-agent",
    name: "User Behavior Agent",
    kind: "agent",
    version: "v3.0.2",
    owner: "SecOps Team",
    status: "restricted",
    risk: "high",
    description: "Aggregates endpoint logs to identify anomalous user behavior indicative of insider threat activity.",
    tags: ["security", "ueba", "anomaly-detection"],
    permissions: {
      filesystem: true,
      network: true,
      email: false,
      calendar: false,
      browser: false,
      shell: false,
      secrets: true,
      external_write: false,
    },
    guardrails: {
      requires_human_approval: true,
      allowed_environments: ["STAGING", "PROD"],
      blocked_actions: ["isolate_host_without_approval"],
      max_autonomy_level: "recommend",
    },
    lifecycle: {
      created_at: "2026-02-12T11:00:00Z",
      approved_at: "2026-02-15T08:00:00Z",
      updated_at: "2026-06-22T13:40:00Z",
    },
    telemetry: {
      executions_30d: 612,
      failure_rate_30d: 0.06,
      avg_latency_ms: 820,
      last_used_at: "2026-06-23T18:02:00Z",
    },
  },
  {
    capability_id: "db-maintenance-tool",
    name: "DB Maintenance Tool",
    kind: "tool",
    version: "v1.3.0",
    owner: "Ops Team",
    status: "draft",
    risk: "high",
    description: "Executes vacuum commands, rebuilds table indices, and prunes old logs from databases.",
    tags: ["database", "maintenance", "sql"],
    permissions: {
      filesystem: true,
      network: false,
      email: false,
      calendar: false,
      browser: false,
      shell: true,
      secrets: true,
      external_write: true,
    },
    guardrails: {
      requires_human_approval: true,
      allowed_environments: ["DEV", "STAGING"],
      blocked_actions: ["drop_database"],
      max_autonomy_level: "execute_with_approval",
    },
    lifecycle: {
      created_at: "2026-06-20T10:00:00Z",
      updated_at: "2026-06-20T10:00:00Z",
    },
    telemetry: {
      executions_30d: 0,
      failure_rate_30d: 0,
      avg_latency_ms: 0,
    },
  },
  {
    capability_id: "log-parser-skill",
    name: "Log Parser Skill",
    kind: "skill",
    version: "v2.0.0",
    owner: "Data Team",
    status: "approved",
    risk: "low",
    description: "Parses system stdout and stderr logs using regex, converting them to JSON schemas.",
    tags: ["utility", "parser", "logs"],
    permissions: {
      filesystem: true,
      network: false,
      email: false,
      calendar: false,
      browser: false,
      shell: false,
      secrets: false,
      external_write: false,
    },
    guardrails: {
      requires_human_approval: false,
      allowed_environments: ["LOCAL", "DEV", "STAGING", "PROD"],
      blocked_actions: [],
      max_autonomy_level: "execute",
    },
    lifecycle: {
      created_at: "2026-01-15T09:00:00Z",
      approved_at: "2026-01-16T12:00:00Z",
      updated_at: "2026-05-10T15:20:00Z",
    },
    telemetry: {
      executions_30d: 14500,
      failure_rate_30d: 0.001,
      avg_latency_ms: 8,
      last_used_at: "2026-06-24T11:48:00Z",
    },
  },
  {
    capability_id: "slack-notifier-tool",
    name: "Slack Notifier Tool",
    kind: "tool",
    version: "v1.1.0",
    owner: "Comms Team",
    status: "approved",
    risk: "low",
    description: "Dispatches automated swarm warnings and alert notifications to corporate channels.",
    tags: ["utility", "notifications", "slack"],
    permissions: {
      filesystem: false,
      network: true,
      email: false,
      calendar: false,
      browser: false,
      shell: false,
      secrets: true,
      external_write: true,
    },
    guardrails: {
      requires_human_approval: false,
      allowed_environments: ["LOCAL", "DEV", "STAGING", "PROD"],
      blocked_actions: [],
      max_autonomy_level: "execute",
    },
    lifecycle: {
      created_at: "2026-04-18T10:00:00Z",
      approved_at: "2026-04-20T08:00:00Z",
      updated_at: "2026-04-20T08:00:00Z",
    },
    telemetry: {
      executions_30d: 4200,
      failure_rate_30d: 0.002,
      avg_latency_ms: 85,
      last_used_at: "2026-06-24T11:40:00Z",
    },
  },
  {
    capability_id: "shell-command-skill",
    name: "Shell Command Skill",
    kind: "skill",
    version: "v1.0.1",
    owner: "Ops Team",
    status: "draft",
    risk: "critical",
    description: "Allows execution of ad-hoc bash and shell scripting directly on the host worker nodes.",
    tags: ["utility", "shell", "ops"],
    permissions: {
      filesystem: true,
      network: true,
      email: true,
      calendar: true,
      browser: true,
      shell: true,
      secrets: true,
      external_write: true,
    },
    guardrails: {
      requires_human_approval: true,
      allowed_environments: ["DEV"],
      blocked_actions: ["rm_rf_root"],
      max_autonomy_level: "draft",
    },
    lifecycle: {
      created_at: "2026-06-22T14:00:00Z",
      updated_at: "2026-06-22T14:00:00Z",
    },
    telemetry: {
      executions_30d: 0,
      failure_rate_30d: 0,
      avg_latency_ms: 0,
    },
  },
  {
    capability_id: "code-analysis-agent",
    name: "Code Analysis Agent",
    kind: "agent",
    version: "v1.2.0",
    owner: "Dev Team",
    status: "draft",
    risk: "high",
    description: "Autonomously audits git branch repositories, scanning for security vulnerabilities and code smells.",
    tags: ["dev", "security", "code-quality"],
    permissions: {
      filesystem: true,
      network: true,
      email: false,
      calendar: false,
      browser: false,
      shell: false,
      secrets: true,
      external_write: false,
    },
    guardrails: {
      requires_human_approval: true,
      allowed_environments: ["LOCAL", "DEV", "STAGING"],
      blocked_actions: ["write_code_to_main_without_pr"],
      max_autonomy_level: "execute_with_approval",
    },
    lifecycle: {
      created_at: "2026-06-24T08:30:00Z",
      updated_at: "2026-06-24T08:30:00Z",
    },
    telemetry: {
      executions_30d: 0,
      failure_rate_30d: 0,
      avg_latency_ms: 0,
    },
  }
];
