import os
import datetime
from pathlib import Path
from typing import Dict, Any

class TaskEvidenceWriter:
    def __init__(self, root_dir: str = "/app"):
        # Make root_dir container-safe
        if os.path.exists("/app"):
            self.root_dir = Path("/app")
        else:
            self.root_dir = Path(root_dir)
            
        self.evidence_dir = self.root_dir / "docs" / "evidence" / "operator-tasks"

    def write_evidence(self, data: Dict[str, Any]) -> str:
        self.evidence_dir.mkdir(parents=True, exist_ok=True)
        
        now = datetime.datetime.now()
        timestamp_str = now.strftime("%Y%m%d-%H%M%S")
        filename = f"{timestamp_str}-shopping-research-print-gate.md"
        filepath = self.evidence_dir / filename
        
        lines = []
        lines.append("# HAS Shopping Research & Print Gate Compliance Evidence")
        lines.append("")
        lines.append(f"**Timestamp**: `{now.strftime('%Y-%m-%d %H:%M:%S')}`")
        lines.append(f"**Task Mode**: `{data.get('mode')}`")
        lines.append(f"**Domain**: `{data.get('domain')}`")
        lines.append(f"**Search Query**: `{data.get('query')}`")
        lines.append("")
        
        lines.append("## Verification Verdict")
        lines.append("")
        lines.append("| Guardrail Check | Status | Details |")
        lines.append("| --- | --- | --- |")
        
        # Blocker verdict
        purchase_block = "PASS" if data.get("purchase_blocked") else "FAIL"
        lines.append(f"| Hard Purchase Block | **{purchase_block}** | Checkout / payments code path blocked. |")
        
        # Safety checks
        safety_status = "PASS" if data.get("safety_pass") else "FAIL"
        lines.append(f"| Product Safety Screen | **{safety_status}** | Checked candidate materials / age ratings. |")
        
        # Print status
        print_status = data.get("print_status", "NOT_TRIGGERED")
        lines.append(f"| Printer Wifi Output | **{print_status}** | HP Wi-Fi printer output state. |")
        lines.append("")
        
        lines.append("## Candidate List")
        lines.append("")
        lines.append("| Rank | Product Title | Price | Safety Screen | URL |")
        lines.append("| --- | --- | --- | --- | --- |")
        for item in data.get("candidates", []):
            prod = item["product"]
            screen = item["safety_result"]
            rank = item["rank"]
            passed_str = "SAFE" if screen["passed"] else "BLOCKED"
            lines.append(f"| {rank} | {prod['title']} | ${prod['price']:.2f} | {passed_str} | [Amazon link]({prod['url']}) |")
            
        lines.append("")
        lines.append("## Blocked Actions Log")
        lines.append("")
        lines.append("The following financial actions are disabled:")
        for act in ["purchase", "checkout", "payment_submission", "bitcoin_transfer"]:
            lines.append(f"- **{act}**: BLOCKED (requires wallet/payment control plane)")
            
        lines.append("")
        lines.append("---")
        lines.append("*Generated by HAS Autopilot Security Gate.*")
        
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
            
        return str(filepath)
