#!/usr/bin/env bash
set -euo pipefail

cd /Users/michaelhoch/hoch_agent_swarm

OUT="has_live_project_tracker/data/goal_blocker_triage.json"

python3 - <<'PY'
import json
import subprocess
from pathlib import Path
from datetime import datetime, timezone

def run(cmd):
    p = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return p.returncode, p.stdout.strip(), p.stderr.strip()

_, git_status, _ = run("git status --short")
latest_log = ""
log_dir = Path("logs/goal_runner")
if log_dir.exists():
    logs = sorted(log_dir.glob("goal_runner_*.log"), key=lambda p: p.stat().st_mtime, reverse=True)
    if logs:
        latest_log = logs[0].read_text(errors="ignore")[-12000:]

blockers = []

if git_status:
    blockers.append({
        "id": "GOAL-BLOCKER-GIT-DIRTY",
        "severity": "MEDIUM",
        "status": "ACTIVE",
        "summary": "Working tree has uncommitted/untracked files generated by UI V2.1, telemetry, watchdog, and GOAL runner work.",
        "safe_next_action": "Review changed files and create staged evidence bundle before commit/tag approval."
    })

if "Metrics are stale" in latest_log:
    blockers.append({
        "id": "GOAL-BLOCKER-LEGACY-METRICS-STALE",
        "severity": "MEDIUM",
        "status": "ACTIVE",
        "summary": "Legacy parallel mirror verifier reads stale metrics even while V2.1 critical telemetry is fresh.",
        "safe_next_action": "Patch legacy verifier or metrics producer to consume freshness_authority critical sources."
    })

if "Run full legacy Playwright diagnostic suite" in latest_log and "STEP_RESULT: FAIL Run full legacy Playwright diagnostic suite" in latest_log:
    blockers.append({
        "id": "GOAL-BLOCKER-LEGACY-UI-TESTS",
        "severity": "LOW",
        "status": "DIAGNOSTIC_ONLY",
        "summary": "Legacy UI tests failed during an explicit diagnostic run. They no longer gate GOAL runner completion.",
        "safe_next_action": "Keep /ui-v2 as primary GOAL command center; refactor legacy cockpit later."
    })

data = {
    "generated_at": datetime.now(timezone.utc).isoformat(),
    "runner": "Michaels AI Model",
    "goal_orchestrator": "michaels-ai-model-goal-orchestrator",
    "goal_state": "DEGRADED_UNTIL_BLOCKERS_CLOSED" if blockers else "GOAL_RUNNER_CLEAR",
    "blocker_count": len(blockers),
    "blockers": blockers,
    "git_status_lines": git_status.splitlines()[:120],
    "latest_goal_runner_log_tail_available": bool(latest_log)
}

Path("has_live_project_tracker/data").mkdir(parents=True, exist_ok=True)
Path("has_live_project_tracker/data/goal_blocker_triage.json").write_text(json.dumps(data, indent=2))
print(json.dumps(data, indent=2))
PY
