import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

const packageJson = JSON.parse(fs.readFileSync("package.json", "utf8"));
const VERSION = packageJson.version;
const RELEASE_DIR = `dist/releases/${VERSION}`;
const MANIFEST_PATH = `${RELEASE_DIR}/release_manifest.json`;
const OUTPUT_NOTES_PATH = `${RELEASE_DIR}/release_notes.md`;

function run(command: string): string {
  try {
    return execSync(command, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return "unknown";
  }
}

function main() {
  console.log(`Generating release notes for version v${VERSION}...`);

  if (!fs.existsSync(MANIFEST_PATH)) {
    console.error(`Error: Release manifest not found at ${MANIFEST_PATH}. Run 'npm run supply:manifest' first.`);
    process.exit(1);
  }

  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));

  // Retrieve validated release candidates from docs/release
  const docsReleaseDir = "docs/release";
  let validationSummary = "";
  if (fs.existsSync(docsReleaseDir)) {
    const files = fs.readdirSync(docsReleaseDir);
    const rcFiles = files
      .filter(f => f.startsWith("rc") && f.endsWith("_validation_result.md"))
      .sort();

    if (rcFiles.length > 0) {
      validationSummary = "### Historical Validation Results\n\n";
      for (const file of rcFiles) {
        const filePath = path.join(docsReleaseDir, file);
        const content = fs.readFileSync(filePath, "utf8");
        // Extract the title or first few lines of the validation doc
        const firstLine = content.split("\n")[0] || "";
        const title = firstLine.replace(/^#\s*/, "").trim();
        validationSummary += `- **[${title}](file:///${path.resolve(filePath)})**\n`;
      }
    }
  }

  // Compile artifacts table
  let artifactsTable = "| Artifact Path | Type | SHA-256 Checksum |\n|---|---|---|\n";
  if (Array.isArray(manifest.artifacts)) {
    for (const art of manifest.artifacts) {
      artifactsTable += `| \`${art.path}\` | \`${art.type}\` | \`${art.sha256}\` |\n`;
    }
  }

  const notesContent = `# Release Notes — v${VERSION}

This document compiles the automated release details, validation reports, and supply-chain integrity posture for version **v${VERSION}** of HOCH Agent Swarm.

---

## Release Metadata
- **Codename:** ${manifest.release?.codename || "Hochster Runtime Audit"}
- **Version:** \`${VERSION}\`
- **Git Commit:** \`${manifest.release?.git_commit_sha || "unknown"}\`
- **Git Branch:** \`${manifest.release?.git_branch || "unknown"}\`
- **Generated At:** \`${manifest.release?.generated_at || new Date().toISOString()}\`
- **CI Provider:** \`${manifest.release?.ci_provider || "local"}\`

---

## Security & Compliance Posture
- **Cosign Signature Status:** \`${manifest.integrity?.signature_status?.toUpperCase() || "UNSIGNED"}\`
- **Waiver Decision ID:** \`${manifest.integrity?.signing_waiver_decision_id || "None"}\`
- **Zero-Drift Status:** \`${manifest.decision?.status || "PASS"}\`

---

## Validated Release Lineage
${validationSummary || "No historical release candidate validation reports found."}

---

## Release Artifacts (Signed Verification Ledger)
${artifactsTable}

---

*Automated release notes generated by \`generate-release-notes.ts\` on ${new Date().toUTCString()}*
`;

  fs.writeFileSync(OUTPUT_NOTES_PATH, notesContent, "utf8");
  console.log(`Successfully wrote release notes to ${OUTPUT_NOTES_PATH}`);
}

main();
