import type { ExecutiveRecommendation } from "./executiveTypes";
import { useGovernanceRegistryStore } from "../governance/aiSystemRegistry";
import { useChaosEngineStore } from "../adversarial/chaosEngine";

export function getDynamicRecommendations(): ExecutiveRecommendation[] {
  const recommendations: ExecutiveRecommendation[] = [];

  // Read current governance systems state
  const { systems } = useGovernanceRegistryStore.getState();
  const criticalSystemsMissingControls = systems.filter(
    (s) => (s.risk_tier === "critical" || s.risk_tier === "high") && s.controls.some((c) => c.status === "missing")
  );

  if (criticalSystemsMissingControls.length > 0) {
    recommendations.push({
      recommendation_id: "dyn-rec-controls",
      title: "Resolve Critical AI Compliance Gaps",
      priority: "critical",
      decision_required: true,
      summary: `Remediate missing controls on high-risk systems: ${criticalSystemsMissingControls.map(s => s.name).join(", ")}.`,
      rationale: `Active AI capabilities are operating with missing NIST AI RMF or NIST 800-53 controls, violating organizational policies.`,
      expected_impact: "Completing control mappings will mitigate system risk levels and raise compliance metrics by up to 15%.",
      evidence_refs: criticalSystemsMissingControls.flatMap(s => s.controls.filter(c => c.status === "missing").map(c => `evidence.${s.system_id}.missing.${c.control_id.toLowerCase()}`)),
      proposed_action: "Access the Control Matrix dashboard to map missing enclaves controls.",
    });
  }

  // Read current red-team scenarios state
  const { scenarios, remediations } = useChaosEngineStore.getState();
  const failedDrills = scenarios.filter((s) => s.result?.status === "failed");
  const openRemediations = remediations.filter((r) => r.status === "open");

  if (failedDrills.length > 0 || openRemediations.length > 0) {
    recommendations.push({
      recommendation_id: "dyn-rec-redteam",
      title: "Patch Red-Team Safety Failures",
      priority: "high",
      decision_required: true,
      summary: `Remediate ${openRemediations.length} safety vulnerabilities generated by failed drills.`,
      rationale: `Automated red-team drills identified bypass risks in active guardrails.`,
      expected_impact: "Remediation patches will restore enclaves security and bring safety assertions back to 100%.",
      evidence_refs: failedDrills.map(d => `scenario.${d.scenario_id}.run.latest`),
      proposed_action: "Deploy safety overrides inside the Vulnerability Remediation dashboard.",
    });
  }

  // Default fallback recommendations if everything is completely clean
  if (recommendations.length === 0) {
    recommendations.push({
      recommendation_id: "dyn-rec-clean",
      title: "Maintain Current Security Posture",
      priority: "low",
      decision_required: false,
      summary: "System enclaves are fully mapped and all safety drills are passing.",
      rationale: "Zero-Trust postures are healthy and audited.",
      expected_impact: "Ensures ongoing compliance readiness.",
      evidence_refs: ["evidence.ledger.verified"],
      proposed_action: "Run regular scheduled audits to prevent drift.",
    });
  }

  return recommendations;
}
