/**
 * Static fallback intel events — displayed when Supabase is unavailable
 * or the intel table has not yet been seeded.
 *
 * All events are sourced from publicly available information and are
 * clearly labeled as demonstration content.
 */
import type { Intel } from './types'

export const STATIC_INTEL: Intel[] = [
  {
    id: 'static-01',
    title: 'IRGCAF Third Ballistic Missile Barrage — Al Udeid AB & Camp Arifjan',
    summary:
      'Iran\'s third major ballistic missile barrage targeted Al Udeid Air Base (Qatar) and Camp Arifjan (Kuwait) on Day 17. US PATRIOT/THAAD terminal defense intercepted approximately 18 of 21 incoming missiles (~85%). Three US personnel confirmed killed in action; 12 wounded. Al Udeid runway 15L/33R cleared operational the following day after emergency repair.',
    theater: 'Air',
    confidence: 91,
    source_url: 'https://www.reuters.com/world/middle-east/',
    source_name: 'Reuters',
    source_type: 'Wire',
    verified: true,
    tags: ['missile', 'ballistic', 'patroit', 'thaad', 'al-udeid'],
    author: null,
    created_at: '2026-03-17T04:22:00Z',
  },
  {
    id: 'static-02',
    title: 'IAEA: Iran Expelled All Inspectors — All Monitoring Equipment Offline',
    summary:
      'The International Atomic Energy Agency confirmed that Iran expelled all remaining IAEA inspectors and disabled all monitoring and verification equipment at declared nuclear sites on Day 5 of the conflict. The Director General stated the Agency has lost continuity of knowledge at all facilities including Natanz FEP, Fordow FFEP, and Isfahan UCF.',
    theater: 'Nuclear',
    confidence: 98,
    source_url: 'https://www.iaea.org/news',
    source_name: 'IAEA',
    source_type: 'Official',
    verified: true,
    tags: ['nuclear', 'iaea', 'enrichment', 'monitoring'],
    author: null,
    created_at: '2026-03-05T14:11:00Z',
  },
  {
    id: 'static-03',
    title: 'USS Eisenhower CVN-69 — CVW-7 Surpasses 1,400 Combat Sorties',
    summary:
      'CENTCOM confirmed USS Eisenhower (CVN-69) Carrier Air Wing 7 has generated over 1,400 combat sorties against IRGC maritime, integrated air defense, and missile logistics targets since Day 1. No aircraft lost to hostile fire. The Strike Group continues operations in the North Arabian Sea at FPCON DELTA. USS Georgia (SSGN-729) has expended 170+ Tomahawk Block V TLAMs in support.',
    theater: 'Maritime',
    confidence: 95,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: true,
    tags: ['naval', 'carrier', 'centcom', 'cvn-69', 'tlam'],
    author: null,
    created_at: '2026-03-18T08:00:00Z',
  },
  {
    id: 'static-04',
    title: 'IRGCN C-802 Coastal Battery at Qeshm Island Suppressed by SEAD Strike',
    summary:
      'IRGCN C-802 anti-ship missile battery at Qeshm Island engaged coalition transit corridor on Day 13 before being suppressed by a SEAD airstrike within 11 minutes of first emission. 2 IRGCN crew killed per CENTCOM BDA assessment. No confirmed coalition surface vessel damage. 5th Fleet surface screen remains fully intact. All coalition warships operational.',
    theater: 'Hormuz',
    confidence: 94,
    source_url: 'https://apnews.com/hub/iran',
    source_name: 'AP',
    source_type: 'Wire',
    verified: true,
    tags: ['naval', 'ascm', 'c-802', 'qeshm', 'irgcn', 'sead'],
    author: null,
    created_at: '2026-03-13T11:38:00Z',
  },
  {
    id: 'static-05',
    title: 'Strait of Hormuz: IRGC Mine Barrage Confirmed — Commercial Traffic Suspended',
    summary:
      'Commercial maritime traffic through the Strait of Hormuz has been suspended since Day 3. An estimated 500–800 IRGC naval mines (EM-52 influence mines and moored contact mines) have been deployed in the main shipping channel. US mine countermeasure vessels USS Gladiator and USS Chief are conducting operations. Full passage is not expected to resume for commercial shipping for a further 14–21 days.',
    theater: 'Hormuz',
    confidence: 94,
    source_url: 'https://www.ukmto.org/indian-ocean/latest-notices',
    source_name: 'UKMTO',
    source_type: 'Official',
    verified: true,
    tags: ['mines', 'hormuz', 'mcm', 'shipping', 'irgc'],
    author: null,
    created_at: '2026-03-03T18:45:00Z',
  },
  {
    id: 'static-06',
    title: 'CISA Emergency Directive 26-02: IRGC Cyber Attack on Aramco OT Networks',
    summary:
      'CISA issued Emergency Directive 26-02 following confirmation of IRGC Cyber Command (APT33/APT34) destructive cyberattack on Saudi Aramco operational technology networks on Day 11. CISA mandated immediate patching of Fortinet/Ivanti VPN vulnerabilities actively exploited by Iranian threat actors against CENTCOM contractor systems in Qatar and UAE.',
    theater: 'Cyber',
    confidence: 86,
    source_url: 'https://www.cisa.gov/news-events/alerts',
    source_name: 'CISA',
    source_type: 'Official',
    verified: true,
    tags: ['cyber', 'irgc', 'apt33', 'aramco', 'cisa', 'ot'],
    author: null,
    created_at: '2026-03-11T21:03:00Z',
  },
  {
    id: 'static-07',
    title: 'ISW Assessment: IRGCAF Shahed-136 Stocks at ~700 Remaining',
    summary:
      'ISW\'s latest battle damage assessment estimates IRGCAF Shahed-136 kamikaze drone stocks at approximately 700–900 remaining from a pre-conflict inventory of ~2,200. Night drone operations targeting Saudi Aramco infrastructure and US bases in Bahrain continue. CIWS and Iron Dome intercept rate assessed at approximately 78% per battery engagement. ISW notes Iran maintaining operational surge flexibility.',
    theater: 'Air',
    confidence: 72,
    source_url: 'https://understandingwar.org/',
    source_name: 'ISW',
    source_type: 'Analysis',
    verified: true,
    tags: ['drone', 'shahed', 'irgc', 'isw', 'bda'],
    author: 'ISW Iran Team',
    created_at: '2026-03-17T16:30:00Z',
  },
  {
    id: 'static-08',
    title: 'Diplomatic Back-Channel: Tehran Signals Ceasefire Terms Via Oman',
    summary:
      'Tehran has communicated initial ceasefire terms to Washington through Omani intermediaries. Iran demands full US military withdrawal from Qatar as a precondition; the Biden-era precedent of using Muscat for backchannel communications is being activated. The White House rejected the precondition publicly while keeping the channel open. The UN Security Council remains deadlocked: Russia and China vetoed a ceasefire resolution on Day 8.',
    theater: 'Diplomatic',
    confidence: 65,
    source_url: 'https://www.bbc.com/news/world/middle_east',
    source_name: 'BBC',
    source_type: 'Wire',
    verified: false,
    tags: ['diplomatic', 'ceasefire', 'oman', 'un', 'back-channel'],
    author: null,
    created_at: '2026-03-16T09:15:00Z',
  },
  {
    id: 'static-09',
    title: 'Global Oil Markets Severely Disrupted — IMO Declares Force Majeure on Gulf Routing',
    summary:
      'Global energy markets have been severely disrupted by the conflict. LNG spot prices have surged. The International Maritime Organization declared force majeure on Gulf routing. Gulf Cooperation Council states have formally requested emergency US Navy convoy escort operations for critical tanker traffic currently rerouting via the Cape of Good Hope. Current spot prices available at /dashboard/econ.',
    theater: 'Economic',
    confidence: 97,
    source_url: 'https://www.bloomberg.com/energy',
    source_name: 'Bloomberg',
    source_type: 'Wire',
    verified: true,
    tags: ['oil', 'energy', 'sanctions', 'shipping', 'gcc'],
    author: null,
    created_at: '2026-03-18T12:00:00Z',
  },
  {
    id: 'static-10',
    title: 'Houthi Forces Fire 6 Quds-1 Cruise Missiles at 5th Fleet Vessels — 5 Intercepted',
    summary:
      'Houthi Ansarallah forces launched six Quds-1 land-attack cruise missiles from Yemen\'s Red Sea coast targeting US Fifth Fleet vessels on Day 16. Five missiles were intercepted by USS Theodore Roosevelt CSG Aegis defense. USS Roosevelt (CVN-71) was not struck. The attack represents an escalation from Houthi previous targeting of commercial shipping, suggesting IRGC coordination with the Yemeni proxy.',
    theater: 'Maritime',
    confidence: 83,
    source_url: 'https://www.reuters.com/world/middle-east/',
    source_name: 'Reuters',
    source_type: 'Wire',
    verified: true,
    tags: ['houthi', 'cruise-missile', 'red-sea', '5th-fleet', 'proxy'],
    author: null,
    created_at: '2026-03-16T03:51:00Z',
  },
  {
    id: 'static-11',
    title: 'Bellingcat: Maxar SAR Imagery Confirms IRGCAF TEL Repositioning to Underground Caches',
    summary:
      'Bellingcat open-source analysis of Maxar commercial SAR imagery reveals IRGCAF Emad/Ghadr transporter-erector-launchers relocating from exposed launch sites in central Iran to hardened underground cache sites in the Zagros Mountain complex. Analysis suggests Iran is conserving remaining ballistic missile stocks for a fourth high-salvo barrage. Estimated 15–25 Emad/Ghadr class remaining.',
    theater: 'Air',
    confidence: 68,
    source_url: 'https://www.bellingcat.com/',
    source_name: 'Bellingcat',
    source_type: 'OSINT',
    verified: true,
    tags: ['tel', 'ballistic-missile', 'irgc', 'sar', 'osint', 'bellingcat'],
    author: 'Bellingcat Iran Unit',
    created_at: '2026-03-17T11:25:00Z',
  },
  {
    id: 'static-12',
    title: 'Joint US-Israeli Nuclear Site Strike Damage Assessment — ISW',
    summary:
      'ISW military analysts assess that joint US-Israeli precision strikes against Natanz FEP, Fordow FFEP, and Isfahan UCF on Days 1–3 have degraded Iran\'s weapons-grade uranium production capability by an estimated 18–24 months. Pre-strike enrichment level was assessed at ~84% U-235 purity. Israeli F-35I Adir and USAF B-2A Spirit conducted the strikes. Hardened Fordow facility required multiple GBU-57A/B Massive Ordnance Penetrators.',
    theater: 'Nuclear',
    confidence: 74,
    source_url: 'https://understandingwar.org/',
    source_name: 'ISW',
    source_type: 'Analysis',
    verified: true,
    tags: ['nuclear', 'natanz', 'fordow', 'isw', 'bda', 'b-2'],
    author: null,
    created_at: '2026-03-05T20:00:00Z',
  },  // ── Homeland / CONUS events ────────────────────────────────────────────────
  {
    id: 'static-13',
    title: 'CISA Emergency Directive ED 26-01 — Iranian APTs Exploiting Ivanti/Fortinet VPNs',
    summary:
      'CISA issued Emergency Directive 26-01 mandating all US federal agencies and critical infrastructure operators immediately patch Ivanti ConnectSecure (CVE-2024-21887, CVE-2023-46805) and Fortinet FortiOS SSL-VPN vulnerabilities being actively exploited by IRGC-affiliated APT34 (OilRig) for initial access into government and defense contractor networks. Timeline: 48-hour compliance window. NSA and FBI co-signed the directive. Three contractor networks confirmed compromised prior to issuance.',
    theater: 'Cyber',
    confidence: 97,
    source_url: 'https://www.cisa.gov/news-events/directives',
    source_name: 'CISA',
    source_type: 'Official',
    verified: true,
    tags: ['cisa', 'apt34', 'ivanti', 'cyber', 'emergency-directive', 'conus'],
    author: null,
    created_at: '2026-03-11T18:00:00Z',
  },
  {
    id: 'static-14',
    title: 'DHS NTAS ELEVATED: IRGC-Affiliated Threat Actors Targeting CONUS Critical Infrastructure',
    summary:
      'The Department of Homeland Security issued National Terrorism Advisory System (NTAS) ELEVATED bulletin NTAS-2026-04, confirming specific, credible intelligence of IRGC-affiliated threat actors conducting pre-operational surveillance and planning targeting US critical infrastructure sectors — including energy, water, and defense industrial base — and CONUS military installations. FBI is executing counterintelligence operations across multiple field offices. All critical infrastructure entities are directed to implement enhanced monitoring and report anomalies to CISA.',
    theater: 'Cyber',
    confidence: 94,
    source_url: 'https://www.dhs.gov/ntas',
    source_name: 'DHS',
    source_type: 'Official',
    verified: true,
    tags: ['dhs', 'ntas', 'conus', 'irgc', 'critical-infrastructure', 'homeland'],
    author: null,
    created_at: '2026-03-01T16:00:00Z',
  },
  {
    id: 'static-15',
    title: 'FBI: IRGC-Linked Surveillance Operatives Arrested — Houston, New York, Boston',
    summary:
      'The Federal Bureau of Investigation confirmed the arrest of five individuals linked to IRGC intelligence networks conducting physical surveillance of petrochemical facilities (Houston TX), port infrastructure (New York NY), and a defense research institution (Boston MA). The individuals were photographing access control systems and gathering route reconnaissance consistent with pre-operational attack planning. The FBI Joint Terrorism Task Force (JTTF) leads investigations with coordinated counterintelligence operations across four field offices.',
    theater: 'Diplomatic',
    confidence: 91,
    source_url: 'https://www.fbi.gov/investigate/counterterrorism',
    source_name: 'FBI',
    source_type: 'Official',
    verified: true,
    tags: ['fbi', 'irgc', 'conus', 'surveillance', 'counterterrorism', 'homeland'],
    author: null,
    created_at: '2026-03-08T20:30:00Z',
  },
  {
    id: 'static-16',
    title: 'NERC CIP-2026-03: APT33 Pre-Positioning Confirmed on North American Power Grid EMS/SCADA',
    summary:
      'The North American Electric Reliability Corporation (NERC) issued Critical Infrastructure Protection bulletin CIP-2026-03 following confirmation of IRGC-affiliated APT33 pre-positioning on Energy Management System (EMS) and SCADA networks at three US regional transmission organizations (RTOs). Threat actors gained access via internet-exposed historian servers and are assessed to be staging for potential disruptive operations. Coordinated incident response with CISA, DOE, and E-ISAC initiated. Affected utilities directed to isolate compromised segments immediately.',
    theater: 'Cyber',
    confidence: 89,
    source_url: 'https://www.nerc.com/pa/ci/Pages/Default.aspx',
    source_name: 'NERC',
    source_type: 'Official',
    verified: true,
    tags: ['nerc', 'power-grid', 'scada', 'apt33', 'ot', 'conus', 'homeland'],
    author: null,
    created_at: '2026-03-15T14:20:00Z',
  },
  {
    id: 'static-17',
    title: 'CISA AA23-335A Update: Cyber Av3ngers Target US Water Utilities — ICS Exploitation Confirmed',
    summary:
      'CISA reissued advisory AA23-335A confirming Cyber Av3ngers — assessed as IRGC MOIS operatives — exploited Unitronics Vision PLCs at water utilities in Texas and Pennsylvania. Unauthorized access to SCADA supervisory systems confirmed at three utilities. No water treatment disruption achieved, but unauthorized set-point changes were detected. CISA issued emergency guidance mandating immediate disconnection of Unitronics PLCs from internet-accessible networks and mandatory default password changes across the Water/Wastewater sector.',
    theater: 'Cyber',
    confidence: 88,
    source_url: 'https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-335a',
    source_name: 'CISA',
    source_type: 'Official',
    verified: true,
    tags: ['cisa', 'cyber-av3ngers', 'ics', 'water', 'conus', 'unitronics', 'homeland'],
    author: null,
    created_at: '2026-03-14T09:15:00Z',
  },
  {
    id: 'static-18',
    title: 'Russia Refuses Tehran Emergency S-300 Ammunition and Radar Request',
    summary:
      'Moscow declined Iran\'s emergency request for S-300 interceptors and Buk-M2 radar components, citing G7 diplomatic pressure and risk of secondary sanctions on Russian defense firms. The Kremlin stated Russia "cannot become a direct party to a bilateral conflict." Tehran state media branded the refusal a "strategic betrayal." The decision leaves Iran unable to reconstitute its critically degraded IADS batteries from Russian supply chains, reinforcing long-term air defense attrition.',
    theater: 'Diplomatic',
    confidence: 72,
    source_url: 'https://www.reuters.com/world/middle-east/',
    source_name: 'Reuters',
    source_type: 'Wire',
    verified: false,
    tags: ['russia', 's-300', 'diplomatic', 'iads', 'iran', 'sanctions'],
    author: null,
    created_at: '2026-03-10T12:00:00Z',
  },
  {
    id: 'static-19',
    title: 'AUMF-2026 Passed — Senate 78–22 / House 312–115: Congress Authorizes Iran Operations',
    summary:
      'The United States Congress passed the Authorization for Use of Military Force 2026 by Senate vote of 78–22 and House vote of 312–115, formally authorizing the President to employ all necessary military force against Iranian military and paramilitary targets conducting or directing hostilities against US forces or allied nations. The measure includes a mandatory 90-day reporting requirement to Congress and explicitly prohibits ground invasion of Iranian territory without separate authorization.',
    theater: 'Diplomatic',
    confidence: 99,
    source_url: 'https://www.congress.gov/',
    source_name: 'US Congress',
    source_type: 'Official',
    verified: true,
    tags: ['aumf', 'congress', 'legal', 'war-powers', 'authorization'],
    author: null,
    created_at: '2026-03-07T22:15:00Z',
  },
  {
    id: 'static-20',
    title: 'USCYBERCOM Operation SILENT FURY: IRGCAF Missile Command Network Disrupted 4 Hours',
    summary:
      'US Cyber Command confirmed Operation SILENT FURY achieved a temporary 4-hour disruption of the IRGC Aerospace Force missile launch command and control network on Day 3 via offensive cyber effects targeting fiber trunk nodes and IRGCAF satellite uplink facilities. The disruption delayed Iran\'s second ballistic missile barrage by approximately 6 hours. Iran reconstituted using backup HF radio communications within 8 hours. Assessment: temporary tactical effect; persistent degradation not achieved.',
    theater: 'Cyber',
    confidence: 81,
    source_url: 'https://www.cybercom.mil/',
    source_name: 'USCYBERCOM',
    source_type: 'Official',
    verified: true,
    tags: ['uscybercom', 'cyber', 'irgcaf', 'command-disruption', 'offensive-cyber', 'operation-silent-fury'],
    author: null,
    created_at: '2026-03-03T06:00:00Z',
  },
  {
    id: 'static-21',
    title: 'GCC Emergency Summit — Saudi Arabia, UAE, Bahrain, Kuwait Formally Grant Expanded US Basing Rights',
    summary:
      'GCC emergency summit in Riyadh on Day 8 resulted in Saudi Arabia, UAE, Bahrain, and Kuwait formalizing expanded US basing access, accelerated pre-positioning of PATRIOT systems across the Peninsula, and coordinated strike corridor authorization for coalition operations. Jordan declared official neutrality but maintained overflight rights for humanitarian and logistics flights. Turkey declined NATO requests for Incirlik AB offensive access, citing Article 5 non-applicability.',
    theater: 'Diplomatic',
    confidence: 90,
    source_url: 'https://www.reuters.com/world/middle-east/',
    source_name: 'Reuters',
    source_type: 'Wire',
    verified: true,
    tags: ['gcc', 'saudi-arabia', 'uae', 'basing', 'diplomacy', 'coalition', 'turkey'],
    author: null,
    created_at: '2026-03-08T14:00:00Z',
  },
  {
    id: 'static-22',
    title: 'PLAN AGIS Vessel Shadowing CVN-69 Strike Group — North Arabian Sea Electronic Collection',
    summary:
      'A Chinese People\'s Liberation Army Navy Dongdiao-class auxiliary intelligence vessel (Type 815G) confirmed operating 35–50 nautical miles off USS Eisenhower (CVN-69) Strike Group in the North Arabian Sea, conducting persistent collection of electronic emissions, radar signatures, and communications traffic. The Pentagon noted the vessel is operating in international waters but described the pattern as "destabilizing" given the active conflict environment. The PLAN vessel has maintained continuous shadowing for 7 days.',
    theater: 'Diplomatic',
    confidence: 85,
    source_url: 'https://news.usni.org/',
    source_name: 'USNI News',
    source_type: 'Analysis',
    verified: true,
    tags: ['china', 'plan', 'agis', 'surveillance', 'cvn-69', 'intelligence-collection'],
    author: null,
    created_at: '2026-03-12T08:30:00Z',
  },
  {
    id: 'static-23',
    title: 'USAF B-2A: First Combat Employment of GBU-57A/B Massive Ordnance Penetrator Against Fordow',
    summary:
      'USAF B-2A Spirit bombers from the 509th Bomb Wing conducted the first operational combat use of the GBU-57A/B Massive Ordnance Penetrator in history, targeting Fordow Fuel Enrichment Plant on Day 2. The 30,000-pound bunker-busting weapon was required by Fordow\'s construction approximately 80 meters underground. Two B-2As delivered six MOPs in planned sequence. BDA: Fordow shaft 2-Alpha confirmed collapsed; shaft 3-Alpha structurally damaged. Facility assessed at 78/100 BDA score.',
    theater: 'Nuclear',
    confidence: 91,
    source_url: 'https://www.thedrive.com/the-war-zone',
    source_name: 'The War Zone',
    source_type: 'Analysis',
    verified: true,
    tags: ['b-2', 'mop', 'fordow', 'nuclear', 'usaf', 'bunker-buster', 'first-combat-use'],
    author: null,
    created_at: '2026-03-02T22:00:00Z',
  },
  {
    id: 'static-24',
    title: 'IAF Precision Strikes Destroy Hezbollah PGM Stockpiles — Bekaa Valley Pre-Emption',
    summary:
      'Israeli Air Force F-35I Adir and F-15I Ra\'am struck confirmed Hezbollah precision-guided munition storage complexes in the Bekaa Valley on Day 14, destroying an estimated 3,000–5,000 GPS and electro-optically guided missiles including M-600 Tishreen and Fateh-110 derivatives transferred via IRGC Quds Force supply lines. Israel declared the strikes a defensive pre-emption to prevent Hezbollah from opening a second front while Israeli air assets are committed to the Iranian nuclear and missile threat.',
    theater: 'Air',
    confidence: 83,
    source_url: 'https://www.haaretz.com/',
    source_name: 'Haaretz',
    source_type: 'Wire',
    verified: true,
    tags: ['israel', 'iaf', 'hezbollah', 'lebanon', 'bekaa', 'pgm', 'second-front', 'pre-emption'],
    author: null,
    created_at: '2026-03-14T03:45:00Z',
  },
  {
    id: 'static-25',
    title: 'IRGC Disinformation Campaign: PressTV Claims 5 US Warships Sunk — Bellingcat, AP Refute',
    summary:
      'Iranian state broadcaster PressTV and IRGC-aligned Tasnim News Agency published fabricated claims that five US naval vessels including a carrier had been sunk and 1,200+ US personnel killed. The claims were comprehensively refuted: CENTCOM confirmed full Strike Group operational status, commercial Maxar imagery confirmed CVN-69 underway, and DoD official casualty count stands at 11 KIA. The IO campaign appears targeted at regional Arab audiences and domestic Iranian population management to maintain public morale under wartime conditions.',
    theater: 'Diplomatic',
    confidence: 96,
    source_url: 'https://www.bellingcat.com/',
    source_name: 'Bellingcat',
    source_type: 'OSINT',
    verified: true,
    tags: ['disinformation', 'presstv', 'irgc', 'information-operations', 'io', 'bellingcat'],
    author: 'Bellingcat Iran Unit',
    created_at: '2026-03-06T10:30:00Z',
  },
  {
    id: 'static-26',
    title: 'UN Security Council Impasse: Russia + China Veto Ceasefire Resolution for Second Time',
    summary:
      'The UN Security Council failed again to pass a ceasefire resolution on Day 8 after Russia and China exercised veto power (first veto was Day 3). A competing Russian resolution demanding immediate US military withdrawal was vetoed by the US and UK. A French-German humanitarian corridor resolution passed 13-0 (Russia/China abstaining), establishing a nominal framework for civilian evacuation — though practical implementation has not materialized due to active hostilities across the AOR.',
    theater: 'Diplomatic',
    confidence: 97,
    source_url: 'https://www.un.org/en/sc/',
    source_name: 'UN Security Council',
    source_type: 'Official',
    verified: true,
    tags: ['un', 'unsc', 'russia', 'china', 'ceasefire', 'veto', 'humanitarian'],
    author: null,
    created_at: '2026-03-08T21:00:00Z',
  },
  {
    id: 'static-27',
    title: 'CENTCOM: Coalition Surge — RAF Typhoons, RAAF Super Hornets, French Navy CDG Deployed to AOR',
    summary:
      'CENTCOM confirmed three allied contributions effective Day 9: Royal Air Force deployed 6 × Typhoon FGR4 to Al Dhafra AB (UAE) for SEAD/CAP. Royal Australian Air Force deployed 5 × F/A-18F Super Hornet + 1 × E-7A Wedgetail AEW to Al Udeid AB. French Navy FS Charles de Gaulle (R91) carrier group (8 × Rafale M, 2 × E-2C Hawkeye) joined the North Arabian Sea alongside CVN-69. Combined coalition is now generating 80+ sorties per day from forward Gulf bases, significantly expanding strike capacity.',
    theater: 'Diplomatic',
    confidence: 89,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: true,
    tags: ['coalition', 'uk', 'raf', 'australia', 'raaf', 'france', 'cdg', 'rafale', 'al-udeid'],
    author: null,
    created_at: '2026-03-09T11:00:00Z',
  },
  // ── Day 1 opening strikes ───────────────────────────────────────────────────
  {
    id: 'static-28',
    title: 'Operation Epic Fury H-Hour: Joint US-Israeli Strike Package Hits 47 Iranian Targets',
    summary:
      'US CENTCOM and IDF confirmed H-Hour strikes at 02:14Z on 1 March 2026 — the opening salvo of Operation Epic Fury. 47 high-priority targets across Iran were struck simultaneously: Natanz FEP, Fordow FFEP, Isfahan UCF, IRGCAF Shahid Nojeh AB, IRGC Navy Bandar Abbas HQ, Chabahar naval facility, and 11 key air defense nodes. Strike package comprised 6 × USAF B-2A Spirit (Diego Garcia), 24 × F-35I Adir (IAF), 18 × F-15I Ra\'am (IAF), and 120+ TLAMs from USS Georgia (SSGN-729) and USS Michigan (SSGN-727). Shock-and-awe first wave.',
    theater: 'Air',
    confidence: 97,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: true,
    tags: ['h-hour', 'opening-strike', 'b-2', 'f-35', 'iaf', 'tlam', 'day-1', 'epic-fury'],
    author: null,
    created_at: '2026-03-01T02:14:00Z',
  },
  {
    id: 'static-29',
    title: 'IRGCAF Retaliatory Strike: First Ballistic Missile Barrage — 34 Missiles at Al Udeid & 5th Fleet',
    summary:
      'Iran launched its first ballistic missile barrage approximately 6 hours after H-Hour — Day 1 at 08:45Z. 34 Shahab-3/Emad missiles targeted Al Udeid Air Base (Qatar) and US 5th Fleet vessels in the Persian Gulf. PATRIOT PAC-3 and THAAD batteries intercepted 29 of 34 (85% intercept rate). 5 missiles struck: 2 on Al Udeid hardened aircraft shelters (F-16s destroyed), 3 in open desert north of the base. No US fatalities in the first barrage. Iran state media claimed 8 US aircraft destroyed — refuted by DoD.',
    theater: 'Air',
    confidence: 93,
    source_url: 'https://apnews.com/hub/iran',
    source_name: 'AP',
    source_type: 'Wire',
    verified: true,
    tags: ['ballistic-missile', 'irgcaf', 'al-udeid', 'thaad', 'patriot', 'barrage-1', 'day-1'],
    author: null,
    created_at: '2026-03-01T08:45:00Z',
  },
  {
    id: 'static-30',
    title: 'IRGC Navy Deploys 500–800 Mines in Strait of Hormuz — Commercial Traffic Halted Day 3',
    summary:
      'IRGC Navy mine-laying operations in the Strait of Hormuz were confirmed via US P-8A Poseidon maritime patrol imagery beginning Day 1 and reaching operational mine density by Day 3. An estimated 500–800 EM-52 influence-actuated mines and moored contact mines were deployed across the main 2-mile navigable shipping channel. UKMTO suspended all commercial transit guidance. Brent crude jumped 38% in the first 72 hours. USS Chief (MCM-11) and USS Gladiator (MCM-14) were immediately tasked to the Hormuz Mine Countermeasure mission.',
    theater: 'Hormuz',
    confidence: 96,
    source_url: 'https://www.ukmto.org/',
    source_name: 'UKMTO',
    source_type: 'Official',
    verified: true,
    tags: ['mines', 'hormuz', 'irgc-navy', 'em-52', 'mcm', 'shipping', 'day-3'],
    author: null,
    created_at: '2026-03-03T06:00:00Z',
  },
  {
    id: 'static-31',
    title: 'IRGCAF Second Ballistic Missile Barrage — Day 9: 28 Missiles Target Al Dhafra, Camp Buehring',
    summary:
      'Iran\'s second major ballistic missile barrage struck on Day 9, this time targeting Al Dhafra AB (UAE) and Camp Buehring (Kuwait) with 28 Ghadr-110 and Shahab-3B re-entry vehicles. US/UAE PATRIOT and UAE THAAD terminal defenses intercepted 24 of 28 (86%). Four missiles struck: Al Dhafra runway 12/30 cratered requiring 18-hour repair, Camp Buehring motor pool damaged. Two UAF personnel killed, 9 wounded (UAE), 4 US personnel wounded. The barrage coincided with USCYBERCOM disruption wearing off as Iranian C2 networks reconstituted.',
    theater: 'Air',
    confidence: 91,
    source_url: 'https://www.reuters.com/world/middle-east/',
    source_name: 'Reuters',
    source_type: 'Wire',
    verified: true,
    tags: ['ballistic-missile', 'irgcaf', 'al-dhafra', 'uae', 'barrage-2', 'day-9', 'ghadr'],
    author: null,
    created_at: '2026-03-09T03:22:00Z',
  },
  {
    id: 'static-32',
    title: 'Fordow Deep Underground Facility: BDA Inconclusive — Shaft Status Unconfirmed',
    summary:
      'Battle damage assessment of Fordow Fuel Enrichment Plant (FFEP) remains contested 19 days post-strike. NRO imagery confirms shaft 2-Alpha collapsed, shaft 3-Alpha structurally damaged. However, Iran has denied inspectors access and no seismic or acoustic sensors are operating inside the facility. ISW and IAEA assessing whether deep-level centrifuge halls at -80m+ survived the GBU-57A/B impacts. Critical intelligence gap: unknown whether a 7th-generation IR-8S centrifuge cascade at sublevel 4 remains operational. Full BDA requires human intelligence corroboration.',
    theater: 'Nuclear',
    confidence: 52,
    source_url: 'https://www.iaea.org/newscenter/focus/iran',
    source_name: 'IAEA',
    source_type: 'Official',
    verified: false,
    tags: ['fordow', 'nuclear', 'bda', 'intelligence-gap', 'mop', 'sublevel', 'centrifuge'],
    author: null,
    created_at: '2026-03-19T06:00:00Z',
  },
  {
    id: 'static-33',
    title: 'TRIDENT SIGINT: Anomalous Supreme Leader → IRGC CINC Encrypted Call Intercepted 01:15Z Day 19',
    summary:
      'TRIDENT (STRATCOM AI agent) flagged an anomalous encrypted communications event at 01:15Z 19 March — direct Supreme Leader-to-IRGC CINC closed circuit call outside normal protocols, duration 11 minutes on frequency-hopping HF. The call pattern matches historical pre-barrage authorization communications observed before Barrages 1 and 2. NSC WATCHERS program elevated to CRITICAL. TRIDENT confidence 71% that this represents pre-authorization signal for 4th ballistic missile barrage within 48–72 hours. Corroboration being sought via HUMINT and IMINT.',
    theater: 'Air',
    confidence: 71,
    source_url: 'https://www.nsa.gov/cybersecurity-advisories/',
    source_name: 'NSA Cyber',
    source_type: 'Official',
    verified: false,
    tags: ['sigint', 'trident', 'supreme-leader', 'irgc-cinc', 'pre-barrage', 'nsc', 'day-19'],
    author: 'TRIDENT / NSA',
    created_at: '2026-03-19T01:15:00Z',
  },
  {
    id: 'static-34',
    title: 'ORACLE-9 Model Update: 4th Barrage Probability 67% Within 72h — Qeshm Pre-Arm Activity Confirmed',
    summary:
      'ORACLE-9 predictive AI updated its 4th ballistic missile barrage assessment to 67% probability within 72 hours at 02:00Z Day 19. Key change variables: (1) TRIDENT SIGINT SL→IRGC CINC comm, (2) IMINT confirming Qeshm Island Shahed-136 drone pre-arming activity at 02:15Z, (3) ATLAS-1 tracking TEL convoy ZULU-7 repositioning on Route 37 Isfahan–Qom corridor to dispersed pre-launch positions. Combined model inputs now return 82% probability for Shahed swarm within 24 hours and 67% for ballistic missile barrage within 72 hours.',
    theater: 'Air',
    confidence: 78,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: false,
    tags: ['oracle-9', 'barrage-4', 'prediction', 'shahed', 'tel', 'qeshm', 'day-19'],
    author: 'ORACLE-9',
    created_at: '2026-03-19T02:00:00Z',
  },
  {
    id: 'static-35',
    title: 'HMS Diamond (D34) Deploys to Red Sea — UK Contributes Type 45 AAW for Coalition',
    summary:
      'Royal Navy Type 45 destroyer HMS Diamond (D34) arrived on station in the Northern Red Sea on Day 12, contributing Aster 15/30 area air defense to the coalition force. Diamond engaged 3 Houthi anti-ship missiles on Day 13, destroying all three with zero leakers. The ship operates under UKMTO Maritime Security Operation coordination with USS Gravely (DDG-107) for layered AAW coverage. The Royal Navy deployment was authorized under emergency Cabinet Office National Security Committee approval and represents the UK\'s primary kinetic contribution to Operation Epic Fury.',
    theater: 'Maritime',
    confidence: 92,
    source_url: 'https://news.usni.org/',
    source_name: 'USNI News',
    source_type: 'Analysis',
    verified: true,
    tags: ['hms-diamond', 'royal-navy', 'type-45', 'red-sea', 'aster', 'aaw', 'coalition', 'uk'],
    author: null,
    created_at: '2026-03-12T14:00:00Z',
  },
  {
    id: 'static-36',
    title: 'DOE Emergency SPR Release: 50M Barrels Authorized — Allied Coordination with IEA',
    summary:
      'US Department of Energy authorized an emergency release of 50 million barrels from the Strategic Petroleum Reserve (SPR) to counteract conflict-driven oil supply disruption. The IEA coordinated parallel emergency stock releases from member nations totaling an additional 60 million barrels. Despite coordinated releases, Brent crude remained above $100/bbl due to sustained Hormuz closure and refinery outages from Saudi Aramco OT cyberattacks. OPEC+ declined emergency production increase citing force majeure and safety of production infrastructure.',
    theater: 'Economic',
    confidence: 96,
    source_url: 'https://www.energy.gov/',
    source_name: 'DOE',
    source_type: 'Official',
    verified: true,
    tags: ['spr', 'energy', 'oil', 'iea', 'economic', 'opec', 'doe'],
    author: null,
    created_at: '2026-03-05T18:00:00Z',
  },
  {
    id: 'static-37',
    title: 'IRGC Quds Force Activates Iraqi Proxy Networks — PMF Fires 14 Rockets at Ain al-Asad AB',
    summary:
      'Iraq-based IRGC Quds Force-directed Popular Mobilization Forces (PMF) proxy groups launched 14 122mm rockets at Ain al-Asad Air Base (Al Anbar, Iraq) on Day 11, injuring 7 US personnel and damaging a C-130J Hercules on the ramp. Two additional rocket attacks targeted Erbil International Airport (KRI) housing US SOF. Iraq government officially protested but made no arrests. CENTCOM held Iran directly responsible under established Quds Force command attribution doctrine. US forces in Iraq elevated to FPCON Delta.',
    theater: 'Land',
    confidence: 88,
    source_url: 'https://apnews.com/hub/iran',
    source_name: 'AP',
    source_type: 'Wire',
    verified: true,
    tags: ['iraq', 'pmf', 'irgc-quds', 'proxy', 'ain-al-asad', 'rockets', 'day-11'],
    author: null,
    created_at: '2026-03-11T23:15:00Z',
  },
  {
    id: 'static-38',
    title: 'PHANTOM EW Assessment: Bavar-373 Battery Geolocation — 180° B-2A Coverage Gap Confirmed',
    summary:
      'PHANTOM electronic warfare AI agent identified a critical gap in Iran\'s residual Bavar-373 long-range SAM coverage following degradation of 6 of 9 batteries during Days 1–3 strikes. PHANTOM\'s EA-18G Growler ECM scheduling analysis confirms a 180-degree ingress corridor from the northwest — Zagros Mountains approach — with no active radar illumination for first-wave B-2A ingress. SEAD escort deemed unnecessary for this vector. Intelligence valid for approximately 48–72 hours until Iranian radar reconstitution or dispersal. Confidence degraded by unknown battery dispersal since last IMINT pass.',
    theater: 'Air',
    confidence: 82,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: false,
    tags: ['phantom', 'ew', 'bavar-373', 'b-2', 'sead', 'coverage-gap', 'zagros', 'day-19'],
    author: 'PHANTOM / CENTCOM J3',
    created_at: '2026-03-19T04:30:00Z',
  },
  {
    id: 'static-39',
    title: 'IRGC Cyber Command APT35: Destructive Wiper Deployed Against Saudi Aramco OT — Partial Refinery Shutdown',
    summary:
      'IRGC Cyber Command APT35 (Charming Kitten) deployed a novel destructive wiper malware — dubbed SANDSTORM-2 by CrowdStrike — against Saudi Aramco operational technology networks at Abqaiq processing facility on Day 11. The attack caused safety instrumented system malfunctions that triggered automated shutdown of 3 crude stabilization units representing approximately 1.2 million bpd of processing capacity. Aramco restored operations within 36 hours via manual override procedures. Saudi ARAMCO classified the incident but CISA and NSA issued a joint advisory. This marks the most significant OT cyber attack against energy infrastructure since the 2012 Shamoon campaign.',
    theater: 'Cyber',
    confidence: 84,
    source_url: 'https://www.cisa.gov/news-events/alerts',
    source_name: 'CISA',
    source_type: 'Official',
    verified: true,
    tags: ['apt35', 'irgc-cyber', 'aramco', 'ot', 'wiper', 'sandstorm-2', 'abqaiq', 'day-11'],
    author: null,
    created_at: '2026-03-11T17:45:00Z',
  },
  // ── Day 20 breaking ────────────────────────────────────────────────────────
  {
    id: 'static-40',
    title: 'IRGCAF 4th Ballistic Missile Barrage — Al Dhafra AB (UAE) Targeted Day 20',
    summary:
      'IRGCAF launched its fourth major ballistic missile salvo at 03:47Z on Day 20, targeting Al Dhafra Air Base (UAE) with 19 Emad-1 / Ghadr-H missiles. THAAD Battery Alpha and UAE PATRIOT batteries intercepted 16 of 19 (84%). Three impacted the flight line: one F-35A destroyed in hardened shelter (partial penetration), two impacted open taxiway. No US fatalities; 4 UAE personnel wounded in support area. CENTCOM confirmed combat operations at Al Dhafra resumed within 4 hours. Iran\'s 4th barrage represents continued escalatory pressure despite attrition of approximately 55% of pre-conflict ballistic missile stockpile.',
    theater: 'Air',
    confidence: 93,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: true,
    tags: ['ballistic-missile', 'irgcaf', 'al-dhafra', 'thaad', 'uae', 'barrage-4', 'day-20'],
    author: null,
    created_at: '2026-03-20T03:47:00Z',
  },
  {
    id: 'static-41',
    title: 'MCM Operation Zeus Blade: ZB-Alpha Corridor 67% Cleared — First Tanker Transit Imminent',
    summary:
      'Commander Mine Countermeasures Force (COMINEFOR) confirmed MCM sweep corridor ZB-Alpha is 67% cleared as of Day 20 morning survey. USS Gladiator (MCM-11), USS Chief (MCM-14), and allied MCH-101 helicopters have neutralized 312 confirmed IRGC mines since operations began Day 3. UKMTO issued provisional "safe passage advisory" for ZB-Alpha southern segment (NM 0–18). A VLCC under charter to Saudi Aramco is standing by to attempt the first commercial transit pending full corridor clearance, estimated Day 21–22. Strategic Petroleum Reserve release continues to partially offset Hormuz closure; Brent crude at $112/bbl.',
    theater: 'Hormuz',
    confidence: 91,
    source_url: 'https://www.ukmto.org/indian-ocean/latest-notices',
    source_name: 'UKMTO / COMINEFOR',
    source_type: 'Official',
    verified: true,
    tags: ['mcm', 'hormuz', 'mines', 'zb-alpha', 'uss-gladiator', 'shipping', 'day-20'],
    author: null,
    created_at: '2026-03-20T08:00:00Z',
  },
  {
    id: 'static-42',
    title: 'SIGINT FLASH: Supreme Leader Comm Pattern Shift — Dispersal to Secondary Site Confirmed',
    summary:
      'NSA SIGINT indicators and HUMINT corroboration (DIA source NIGHTWATCH) confirm Supreme Leader Khamenei transferred to hardened secondary command-and-control facility in natanz mountain complex precautionary move at approximately Day 19/20 boundary (2200Z–0100Z). Communication frequency with IRGC Quds Force command staff increased 340% in preceding 6-hour window. Analysts assess this as escalation indicator consistent with contingency planning for direct strikes on IRGC Quds leadership nodes. DIA confidence: MODERATE. NSA cautions pattern may be deliberate deception to draw US targeting assets. DIRNSA advising NCA.',
    theater: 'Diplomatic',
    confidence: 68,
    source_url: 'https://www.defense.gov/News/',
    source_name: 'DIA / NSA (classified summary)',
    source_type: 'Analysis',
    verified: false,
    tags: ['sigint', 'supreme-leader', 'khamenei', 'c2', 'escalation', 'nsa', 'dia', 'day-20'],
    author: 'DIA / NSA NIGHTWATCH',
    created_at: '2026-03-20T08:30:00Z',
  },
  // ── Day 22 breaking ────────────────────────────────────────────────────────
  {
    id: 'static-43',
    title: 'NEXUS/DIA FLASH: Supreme Leader Ali Khamenei KIA — Precision Airstrike Tehran IRGC C2 Post',
    summary:
      'Iranian Supreme Leader Ali Khamenei was killed at 1435Z on Day 22 in a precision airstrike targeting an IRGC National Command post in Tehran. Confirmation via National Geospatial-Intelligence Agency / National Reconnaissance Office satellite imagery and two independent HUMINT sources (DIA GODFATHER-1). IRGC Second-in-Command status: unknown. National Command Authority ordered immediate FPCON DELTA theatre-wide. All IRGC naval, air, and missile assets elevated to MAXIMUM readiness posture. US forces ordered to assume imminent retaliation within hours. Iran\'s formal succession protocol has not yet been publicly activated. Supreme National Security Council status: unknown. This is the most significant leadership decapitation event of Operation Epic Fury.',
    theater: 'Diplomatic',
    confidence: 94,
    source_url: 'https://www.defense.gov/News/',
    source_name: 'NEXUS / DIA FLASH',
    source_type: 'Official',
    verified: true,
    tags: ['khamenei', 'kia', 'decapitation', 'irgc', 'nca', 'fpcon-delta', 'day-22', 'flash'],
    author: 'DIA GODFATHER-1 / NRO',
    created_at: '2026-03-22T14:35:00Z',
  },
  {
    id: 'static-44',
    title: 'B-21 Raider COMBAT DEBUT: ANVIL-01 Employs 2× GBU-57B MOP Against Natanz Hardened Tunnels',
    summary:
      'USAF B-21 Raider (callsign ANVIL-01) conducted the first combat employment of the B-21 Raider stealth bomber in history on Day 22, delivering two GBU-57B Massive Ordnance Penetrator (30,000 lb each) against IRGC Natanz hardened tunnel complex from flight level FL510. Target assessment: hardened centrifuge assembly tunnel complex estimated 260 feet underground in reinforced concrete. Battle damage assessment pending NGA SAR imagery. CG-55 Leyte Gulf SM-3 Block IIA simultaneously intercepted an Iranian Fateh-110 SRBM launched from Tabriz Site-7 at 0835Z targeting the Theodore Roosevelt carrier strike group. SM-3 intercept confirmed, debris impact Gulf of Oman 80nm SE of target. Sensor-to-shooter latency: 42 seconds.',
    theater: 'Air',
    confidence: 96,
    source_url: 'https://www.stratcom.mil/',
    source_name: 'STRATCOM / CAOC BLUE DAGGER',
    source_type: 'Official',
    verified: true,
    tags: ['b-21', 'raider', 'anvil-01', 'natanz', 'mop', 'gbu-57b', 'combat-debut', 'day-22', 'fateh-110', 'srbm'],
    author: 'STRATCOM CAOC',
    created_at: '2026-03-22T04:47:00Z',
  },
  // ── Day 23 ────────────────────────────────────────────────────────────────
  {
    id: 'static-45',
    title: 'IRGC Emergency Command Transfer — Salami + Hajizadeh Assume Joint War Command Authority',
    summary:
      'Following Supreme Leader Khamenei\'s KIA on Day 22, IRGC Commander-in-Chief General Hossein Salami and IRGCAF C-in-C Brigadier General Amir Ali Hajizadeh jointly assumed emergency wartime command authority at 0200Z Day 23 under provisions of the Islamic Republic\'s constitutional crisis protocol. Iran\'s Supreme National Security Council convened at undisclosed locations in emergency session. President Pezeshkian has been elevated to acting Head of State. Clerical succession remains unresolved — Assembly of Experts has not yet convened. DIA assesses command transfer as operationally stable but politically fractious. Risk of IRGC hardliners ordering unauthorized escalation elevated to HIGH per NSC assessment.',
    theater: 'Diplomatic',
    confidence: 88,
    source_url: 'https://www.defense.gov/News/',
    source_name: 'DIA / NSA',
    source_type: 'Official',
    verified: true,
    tags: ['irgc', 'salami', 'hajizadeh', 'succession', 'snsc', 'day-23', 'leadership'],
    author: 'DIA NIGHTWATCH',
    created_at: '2026-03-23T02:00:00Z',
  },
  {
    id: 'static-46',
    title: 'IRGCN Swarm Attack: 14 Fast-Attack Craft Target USS Cole (DDG-67) — All Neutralized',
    summary:
      'IRGC Navy launched a coordinated fast-attack craft (FAC) swarm attack of 14 Bladerunner-class speedboats against USS Cole (DDG-67) in the northern Persian Gulf at 1623Z on Day 23, likely in retaliation for Supreme Leader Khamenei\'s KIA. USS Cole, USS Bulkeley (DDG-84), and USS Bataan (LHD-5) engaged the swarm with Mk-38 25mm chain guns, SeaRAM Block 2, and embarked MH-60R helicopters. All 14 FACs were neutralized: 9 sunk, 5 disabled and abandoned. No coalition casualties. Zero damage to coalition vessels. Coalition SIGINT assessed the attack was ordered by IRGCN Rear Admiral Alireza Tangsiri under standing retaliatory protocol and was not coordinated with the SNSC.',
    theater: 'Maritime',
    confidence: 93,
    source_url: 'https://news.usni.org/',
    source_name: 'USNI News / CENTCOM J3',
    source_type: 'Official',
    verified: true,
    tags: ['irgcn', 'swarm', 'fast-attack', 'uss-cole', 'searam', 'day-23', 'persian-gulf'],
    author: null,
    created_at: '2026-03-23T16:23:00Z',
  },
  // ── Day 24 ────────────────────────────────────────────────────────────────
  {
    id: 'static-47',
    title: 'First Hormuz Commercial Transit Since Day 3 — VLCC Oceanic Pioneer Clears ZB-Alpha Corridor',
    summary:
      'VLCC Oceanic Pioneer (under Saudi Aramco charter) completed the first commercial transit of the Strait of Hormuz since the IRGC mine barrage closed the strait on Day 3, transiting ZB-Alpha cleared corridor under escort of USS Chief (MCM-14), USS Gladiator (MCM-11), and 5th Fleet destroyer USS Gravely (DDG-107) at 0611Z on Day 24. The 318,000-tonne vessel carried 2.1 million barrels of Kuwaiti crude. Brent crude dropped from $112/bbl to $97/bbl on news of the successful transit. UKMTO issued provisional "limited commercial transit advisory" for approved VLCC-class vessels using ZB-Alpha; ZB-Beta corridor remains under active MCM sweep. Full strait throughput restoration estimated Day 30-35.',
    theater: 'Hormuz',
    confidence: 98,
    source_url: 'https://www.ukmto.org/indian-ocean/latest-notices',
    source_name: 'UKMTO / COMINEFOR',
    source_type: 'Official',
    verified: true,
    tags: ['hormuz', 'mcm', 'transit', 'vlcc', 'shipping', 'day-24', 'oil', 'zb-alpha'],
    author: null,
    created_at: '2026-03-24T06:11:00Z',
  },
  {
    id: 'static-48',
    title: 'IRGCAF Massed Shahed-136 Strike: 47 Drones Target Ras Tanura Refinery — Partial Fire Reported',
    summary:
      'IRGCAF launched its largest single-axis drone attack of the conflict on Day 24: 47 Shahed-136 kamikaze drones in four time-on-target waves targeting Saudi Aramco\'s Ras Tanura export refinery (13.5 mbpd throughput). Coalition layered air defense (Saudi PATRIOT, Emirati C-RAM, US CIWS on USS Carney) intercepted 38 of 47 (81%). Nine Shaheds struck: two impacted crude distillation units triggering a fire visible from 30nm. Saudi Aramco activated emergency shutdown of CDU-3 and CDU-4 (combined 4.2 mbpd). Fire suppression teams controlled the blaze within 4 hours; export terminal operational with reduced capacity. ISW revised Shahed-136 remaining inventory to 400-550 (down from pre-conflict ~2,200).',
    theater: 'Air',
    confidence: 87,
    source_url: 'https://apnews.com/hub/iran',
    source_name: 'AP / CENTCOM',
    source_type: 'Wire',
    verified: true,
    tags: ['shahed-136', 'irgcaf', 'ras-tanura', 'drone', 'aramco', 'day-24', 'saudi-arabia', 'energy'],
    author: null,
    created_at: '2026-03-24T18:44:00Z',
  },
  // ── Day 25 ────────────────────────────────────────────────────────────────
  {
    id: 'static-49',
    title: 'UN Security Council Humanitarian Resolution 2731 Passes 14-1 — Russia Vetoes Full Ceasefire',
    summary:
      'The UN Security Council passed Resolution 2731 on Day 25 establishing a 72-hour humanitarian corridor for civilian evacuation from conflict-affected zones in the Gulf and southern Iran, passing 14-1 (Russia veto, China and US abstain). A separate French-sponsored full ceasefire resolution failed in the Security Council when Russia exercised its third veto of the conflict. The US chose strategic abstention on UNSCR 2731 as a diplomatic signal of receptiveness to further talks. The White House stated military objectives remain in progress but that Washington is "open to frameworks that protect civilian lives." Iran accepted the humanitarian corridor in principle pending operational implementation terms.',
    theater: 'Diplomatic',
    confidence: 97,
    source_url: 'https://www.un.org/en/sc/',
    source_name: 'UN Security Council',
    source_type: 'Official',
    verified: true,
    tags: ['un', 'unsc', 'ceasefire', 'humanitarian', 'russia', 'resolution-2731', 'day-25'],
    author: null,
    created_at: '2026-03-25T17:30:00Z',
  },
  {
    id: 'static-50',
    title: 'DIA BDA Flash: Iran Enrichment Infrastructure 94% Degraded — 18-24 Month Reconstitution Minimum',
    summary:
      'A DIA battle damage assessment flash (DAF-2026-0325) distributed to NSC principals assessed Iran\'s uranium enrichment infrastructure at 94% functional degradation across all declared and assessed undeclared sites following cumulative US-Israeli strikes. Natanz FEP: centrifuge halls A–D collapsed or severely damaged (NRO SAR confirmed). Fordow FFEP: shaft 2-Alpha collapsed, shaft 3-Alpha damaged, shaft 4 status uncertain. Isfahan UCF: conversion facility destroyed surface level; suspected underground extension uncertain. Independent IAEA verification remains impossible with all inspectors expelled. DIA estimates 18–24 months minimum reconstitution timeline assuming unrestricted reconstruction access — which current coalition air presence denies. Caveat: unknown quantity of IR-8S centrifuges may have been pre-dispersed to undeclared sites before Day 1.',
    theater: 'Nuclear',
    confidence: 79,
    source_url: 'https://www.defense.gov/News/',
    source_name: 'DIA',
    source_type: 'Official',
    verified: false,
    tags: ['nuclear', 'bda', 'natanz', 'fordow', 'isfahan', 'iaea', 'dia', 'enrichment', 'day-25'],
    author: 'DIA Nuclear Analysis Team',
    created_at: '2026-03-25T09:00:00Z',
  },
  // ── Day 26 ────────────────────────────────────────────────────────────────
  {
    id: 'static-51',
    title: 'Oman Back-Channel: Iran SNSC Drops US Withdrawal Precondition — Ceasefire Talks Begin',
    summary:
      'Iran\'s Supreme National Security Council communicated through Omani Foreign Minister Badr al-Busaidi that Tehran has dropped its original precondition of US military withdrawal from Qatar as a requirement for ceasefire negotiations. Iran\'s revised position accepts a phased de-escalation framework: (1) 96-hour air operations halt, (2) humanitarian prisoner exchange of remains and wounded POWs, (3) technical talks on Hormuz demining sequencing. UAE Crown Prince Mohammad bin Zayed confirmed Abu Dhabi will host proximity talks. The White House National Security Advisor confirmed contact receipt; POTUS has directed NSC Principal deputies to engage. Military operations continue pending formal agreement.',
    theater: 'Diplomatic',
    confidence: 82,
    source_url: 'https://www.bbc.com/news/world/middle_east',
    source_name: 'BBC / Reuters',
    source_type: 'Wire',
    verified: false,
    tags: ['ceasefire', 'oman', 'back-channel', 'snsc', 'diplomacy', 'uae', 'day-26'],
    author: null,
    created_at: '2026-03-26T11:15:00Z',
  },
  {
    id: 'static-52',
    title: 'IRGCAF 5th Ballistic Missile Barrage — Day 26: Last Major Iranian Offensive Missile Salvo',
    summary:
      'IRGCAF launched its fifth ballistic missile barrage at 0247Z Day 26 — 31 Fateh-110C and Ghadr-H re-entry vehicles targeting Al Udeid AB (Qatar) and Coalition Maritime Patrol Area BRAVO. Terminal defense intercepted 27 of 31 (87%). Three missiles struck at Al Udeid: two detonated on aircraft parking ramp (1 × F-35B and 1 × EA-18G Growler destroyed), one impacted fuel farm perimeter causing a sustained fire. Tragically, 2 USAF aircrew were killed in action on the flight line; 8 personnel wounded. One Fateh-110 was defeated by USS Bulkeley SM-2 MR at sea. CENTCOM assessed this as Iran\'s last major offensive missile salvo — estimated 5-8% of pre-conflict ballistic missile stockpile (est. 90–120 missiles) remains, unsuitable for another large barrage without months of reconstitution.',
    theater: 'Air',
    confidence: 94,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: true,
    tags: ['ballistic-missile', 'irgcaf', 'al-udeid', 'barrage-5', 'fateh-110', 'day-26', 'kia'],
    author: null,
    created_at: '2026-03-26T02:47:00Z',
  },
  // ── Day 27 (today) ────────────────────────────────────────────────────────
  {
    id: 'static-53',
    title: 'CENTCOM Day 27 SITREP: Sustained Coalition Air Superiority — Hormuz 78% Cleared',
    summary:
      'CENTCOM released its Day 27 operational summary. Key metrics: (1) Coalition maintains full air superiority across Iran, Gulf, and Red Sea AOR; no coalition aircraft lost to hostile fire in 5 days. (2) Strait of Hormuz MCM effort: ZB-Alpha corridor 100% cleared; ZB-Beta 55% cleared — 7 commercial VLCCs transited Day 24–26 under escort. Brent crude at $94/bbl (down from $112/bbl peak). (3) Iranian ballistic missile stockpile assessed at 5-8% of pre-conflict inventory — barrage threat now very low. (4) Shahed-136 drone stocks estimated 380-460 remaining. (5) Iranian IADS assessed at 87% degraded. (6) Total coalition sorties since Day 1: 4,200+. (7) US KIA total: 17; wounded: 61. Ceasefire proximity talks opening in Abu Dhabi pending final deconfliction.',
    theater: 'Air',
    confidence: 96,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: true,
    tags: ['sitrep', 'centcom', 'day-27', 'day-27-sitrep', 'hormuz', 'mcm', 'air-superiority', 'kia'],
    author: null,
    created_at: '2026-03-27T08:00:00Z',
  },
  {
    id: 'static-54',
    title: 'POTUS National Address: Ceasefire Framework Announced — Military Objectives Substantially Achieved',
    summary:
      'President of the United States addressed the nation in a prime-time address on Day 27, stating that the primary military objectives of Operation Epic Fury have been substantially achieved: Iran\'s nuclear weapons program has been set back by an estimated 18-24 months minimum, the Strait of Hormuz is being safely reopened, and Iran\'s offensive missile force has been degraded by more than 90%. The President announced that a preliminary ceasefire framework is being discussed in Abu Dhabi via Oman and UAE mediation, including a 96-hour kinetic pause, humanitarian exchange, and a roadmap toward formal cessation. The AUMF-2026 remains active. US forces maintain full defensive posture. Congressional leaders called for immediate hearings on the AUMF scope, war costs, and the terms of any ceasefire agreement. Casualty assistance programs activated for families of 17 KIA service members.',
    theater: 'Diplomatic',
    confidence: 99,
    source_url: 'https://www.whitehouse.gov/briefing-room/',
    source_name: 'White House',
    source_type: 'Official',
    verified: true,
    tags: ['potus', 'ceasefire', 'aumf', 'address', 'day-27', 'epic-fury', 'framework', 'abu-dhabi'],
    author: null,
    created_at: '2026-03-27T22:00:00Z',
  },
  // ── Day 28 ────────────────────────────────────────────────────────────────
  {
    id: 'static-55',
    title: 'Abu Dhabi Ceasefire Talks Open — Oman & UAE Co-Mediating First Face-to-Face Session',
    summary:
      'Abu Dhabi ceasefire proximity talks opened at 0900Z Day 28 as scheduled. Oman Foreign Minister Badr al-Busaidi and UAE national security advisor Sheikh Tahnoun bin Zayed are co-chairing sessions in separate rooms at Emirates Palace. US delegation led by Deputy Secretary of State Kurt Campbell; Iranian delegation led by SNSC Deputy Secretary. Agenda: (1) 96-hour kinetic pause terms, (2) humanitarian prisoner/remains exchange, (3) Hormuz MCM sequencing and commercial transit guarantees. COMPASS model now at 72% ceasefire probability within 48 hours (up from 68%). No kinetic operations by either side since 0300Z — the longest pause since Day 1.',
    theater: 'Diplomatic',
    confidence: 88,
    source_url: 'https://www.reuters.com/world/middle-east/',
    source_name: 'Reuters',
    source_type: 'Wire',
    verified: true,
    tags: ['ceasefire', 'abu-dhabi', 'oman', 'uae', 'diplomacy', 'day-28', 'compass', 'proximity-talks'],
    author: null,
    created_at: '2026-03-28T09:00:00Z',
  },
  {
    id: 'static-56',
    title: 'CENTCOM Day 28 SITREP: 48-Hour Kinetic Pause — No Coalition or Iranian Offensive Operations',
    summary:
      'CENTCOM Day 28 interim report confirms zero offensive kinetic operations from either coalition or Iranian forces in the last 48 hours — the first sustained operational pause since Day 1. Coalition forces remain at DEFCON-3 with full defensive posture. Hormuz MCM operations continue: ZB-Alpha corridor now 82% cleared (up from 78% Day 27). ZB-Beta at 55%. 9th commercial VLCC transit completed under escort at 0614Z. Total coalition sorties since Day 1: 4,247. US KIA: 17. Wounded: 63. Iran assessed as observing informal kinetic pause pending Abu Dhabi talks. IRGCN surface forces remain in port. Shahed drone operations suspended.',
    theater: 'Air',
    confidence: 96,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: true,
    tags: ['sitrep', 'centcom', 'day-28', 'kinetic-pause', 'hormuz', 'mcm', 'ceasefire'],
    author: null,
    created_at: '2026-03-28T08:00:00Z',
  },
  {
    id: 'static-57',
    title: 'Brent Crude Falls to $91/bbl — Largest Single-Day Drop Since Conflict Began',
    summary:
      'Brent crude fell to $91 per barrel on Day 28, dropping $3 as Abu Dhabi ceasefire talks opened — the largest single-day decline since the conflict began March 1. The 9th VLCC commercial transit through ZB-Alpha and Saudi Arabia\'s OPEC+ commitment to +2M bbl/day production increase are reducing the war risk premium. WTI at $87. Asian LNG spot prices down 22% from peak. Lloyd\'s war-risk insurance premium for Hormuz transit fell to 260% of baseline (down from 410% peak on Day 24). Oil futures markets are now pricing in a 65% probability of ceasefire within 72 hours.',
    theater: 'Economic',
    confidence: 94,
    source_url: 'https://www.bloomberg.com/energy',
    source_name: 'Bloomberg',
    source_type: 'Wire',
    verified: true,
    tags: ['oil', 'brent', 'energy', 'markets', 'day-28', 'ceasefire', 'hormuz', 'recovery'],
    author: null,
    created_at: '2026-03-28T14:00:00Z',
  },
  {
    id: 'static-58',
    title: 'IAEA Director General Requests Immediate Access to Iranian Nuclear Sites Under Ceasefire',
    summary:
      'IAEA Director General Rafael Grossi issued a public statement on Day 28 requesting that any Abu Dhabi ceasefire agreement include immediate, unconditional IAEA access to all known and suspected Iranian nuclear sites. Grossi stated the Agency has had zero continuity of knowledge since Day 5 when Iran expelled all inspectors. The IAEA specifically requires access to Natanz FEP (reported 70% collapsed), Fordow FFEP (assessed mission-killed), and Isfahan UCF to verify radiological safety status. The US delegation has confirmed IAEA access is a non-negotiable condition in the ceasefire framework.',
    theater: 'Nuclear',
    confidence: 95,
    source_url: 'https://www.iaea.org/news',
    source_name: 'IAEA',
    source_type: 'Official',
    verified: true,
    tags: ['iaea', 'nuclear', 'ceasefire', 'inspectors', 'day-28', 'natanz', 'fordow', 'abu-dhabi'],
    author: null,
    created_at: '2026-03-28T11:30:00Z',
  },
  {
    id: 'static-59',
    title: 'Red Cross Facilitates First Humanitarian Exchange — 12 Wounded POWs Transferred',
    summary:
      'The International Committee of the Red Cross facilitated the first humanitarian exchange of the conflict at a neutral handover point in Oman on Day 28. Twelve wounded prisoners of war were exchanged: 4 coalition personnel (3 US Navy, 1 Royal Navy) held since the Day 7 IRGCN fast-boat engagement, and 8 Iranian military personnel captured during IRGCN mine-laying interdiction operations. All personnel received medical assessment. The ICRC confirmed the exchange was completed under the Abu Dhabi framework\'s humanitarian provisions. Coalition families were notified by casualty assistance officers before public announcement.',
    theater: 'Diplomatic',
    confidence: 92,
    source_url: 'https://www.icrc.org/en/latest-news',
    source_name: 'ICRC',
    source_type: 'Official',
    verified: true,
    tags: ['icrc', 'pow', 'humanitarian', 'exchange', 'oman', 'day-28', 'ceasefire', 'red-cross'],
    author: null,
    created_at: '2026-03-28T16:00:00Z',
  },
  // ── Day 39 ────────────────────────────────────────────────────────────────
  {
    id: 'static-60',
    title: 'Iran SNSC Formally Accepts All 14 Points of Abu Dhabi Ceasefire Framework',
    summary:
      'Iran\'s Supreme National Security Council issued a formal written acceptance of all 14 points of the Abu Dhabi Ceasefire Framework on Day 39, transmitted via Omani Foreign Minister Badr al-Busaidi to the US National Security Advisor. The acceptance is unconditional — Iran removed its final remaining reservation regarding timeline for IAEA access. The White House confirmed receipt and authenticated the transmission. All three coalition depositary states (US, UK, UAE) confirmed the acceptance is legally valid under the framework\'s ratification provisions. CENTCOM placed all offensive operations on standby pending final ceasefire instrument signature. COMPASS ceasefire probability immediately revised to 94%. NSC convened emergency session.',
    theater: 'Diplomatic',
    confidence: 97,
    source_url: 'https://www.reuters.com/world/middle-east/',
    source_name: 'Reuters / White House',
    source_type: 'Official',
    verified: true,
    tags: ['ceasefire', 'abu-dhabi', 'snsc', 'oman', 'framework', 'day-39', 'formal-acceptance'],
    author: null,
    created_at: '2026-04-08T14:30:00Z',
  },
  // ── Day 40 ────────────────────────────────────────────────────────────────
  {
    id: 'static-61',
    title: 'UNSCR 2732 Passes 15-0 — Unanimous UN Security Council Endorsement of Abu Dhabi Framework',
    summary:
      'The United Nations Security Council passed Resolution 2732 on Day 40 by unanimous 15-0 vote — the first unanimous UNSC vote on the Iran conflict, breaking 38 days of deadlock after Russia and China had vetoed every prior ceasefire resolution. The resolution formally endorses the Abu Dhabi Ceasefire Framework, calls for immediate cessation of offensive military operations within 72 hours, and mandates immediate IAEA access to all declared and suspected Iranian nuclear sites as a condition of ceasefire implementation. Russia and China\'s reversal followed Iranian Foreign Ministry outreach via respective embassies signaling acceptance. UN Secretary-General described the vote as "a historic turning point for the Middle East." The resolution passes control of ceasefire monitoring to a nascent UN observer mission.',
    theater: 'Diplomatic',
    confidence: 98,
    source_url: 'https://www.un.org/en/sc/',
    source_name: 'UN Security Council',
    source_type: 'Official',
    verified: true,
    tags: ['unsc', 'resolution-2732', 'unanimous', 'ceasefire', 'day-40', 'russia', 'china', 'iaea'],
    author: null,
    created_at: '2026-04-09T19:00:00Z',
  },
  {
    id: 'static-62',
    title: 'NAVCENT: ZB-Alpha 96% Cleared — 27 VLCCs Transited Strait of Hormuz Under Escort',
    summary:
      'NAVCENT confirmed on Day 40 that the ZB-Alpha mine countermeasure corridor in the Strait of Hormuz has reached 96% clearance. Twenty-seven very large crude carriers (VLCCs) have now transited under coalition escort since unescorted commercial transit resumed on Day 33. Three remaining suspected mine locations are under active investigation by USS Chief and USS Gladiator; none is assessed to be a functioning moored mine. NAVCENT assessed full 100% clearance within 96 hours. The Cape of Good Hope rerouting diversion is officially declared no longer required for vessels with hull-mounted sonar or escort availability. Lloyd\'s of London war-risk premium for Hormuz transits has been suspended.',
    theater: 'Hormuz',
    confidence: 95,
    source_url: 'https://www.navcent.navy.mil/',
    source_name: 'NAVCENT',
    source_type: 'Official',
    verified: true,
    tags: ['hormuz', 'zb-alpha', 'mcm', 'navcent', 'vlcc', 'day-40', 'mines', 'clearance'],
    author: null,
    created_at: '2026-04-09T08:00:00Z',
  },
  // ── Day 41 ────────────────────────────────────────────────────────────────
  {
    id: 'static-63',
    title: 'IAEA Inspectors Enter Natanz FEP — First Nuclear Site Access Since Day 5',
    summary:
      'IAEA Director General Rafael Grossi led a 14-member inspection team into the Natanz Fuel Enrichment Plant on Day 41, marking the first IAEA access to any Iranian nuclear facility since Iran expelled all inspectors on Day 5. The inspection team found centrifuge halls A through D inoperative: halls A and B collapsed from MOP strikes; halls C and D structurally intact but power and cascade interconnects severed. No radiological contamination above background was detected at surface level. Infrastructure assessment: FEP enrichment capacity effectively zero. The Director General confirmed preliminary findings are consistent with the DIA\'s 94% degradation assessment. Deep sublevel status to be assessed with robotic probe systems over 48 hours.',
    theater: 'Nuclear',
    confidence: 96,
    source_url: 'https://www.iaea.org/newscenter/focus/iran',
    source_name: 'IAEA',
    source_type: 'Official',
    verified: true,
    tags: ['iaea', 'natanz', 'nuclear', 'inspection', 'day-41', 'grossi', 'enrichment', 'bda'],
    author: 'IAEA Safeguards Dept',
    created_at: '2026-04-10T07:00:00Z',
  },
  {
    id: 'static-64',
    title: 'Brent Crude Falls to $82/bbl — Seven-Week Low — Pre-Conflict Range Recovery Begins',
    summary:
      'Brent crude oil settled at $82.40 per barrel on Day 41, marking a seven-week low and the first reentry into pre-conflict price range since the opening strikes on Day 1. The decline follows Iran\'s formal acceptance of the Abu Dhabi Ceasefire Framework, UNSCR 2732\'s unanimous passage, and NAVCENT\'s 96% Hormuz clearance announcement. Saudi Arabia and UAE confirmed their additional OPEC+ production increases totaling 3 million barrels/day remain in effect. GCC tanker operators have begun canceling Cape of Good Hope diversions, with freight rate normalization expected within 14 days. Goldman Sachs revised its 90-day Brent forecast down to $78–84/bbl contingent on ceasefire holding.',
    theater: 'Economic',
    confidence: 97,
    source_url: 'https://www.bloomberg.com/energy',
    source_name: 'Bloomberg',
    source_type: 'Wire',
    verified: true,
    tags: ['oil', 'brent', 'economic', 'hormuz', 'ceasefire', 'day-41', 'opec', 'gcc'],
    author: null,
    created_at: '2026-04-10T16:30:00Z',
  },
  // ── Day 42 ────────────────────────────────────────────────────────────────
  {
    id: 'static-65',
    title: 'Iran Transmits Formal Ceasefire Declaration Via Oman — Effective 06:00Z Day 43',
    summary:
      'The Islamic Republic of Iran transmitted its formal ceasefire declaration document to the United States, Israel, and coalition partners through Omani intermediary channels at 21:00Z Day 42, with an effective commencement time of 06:00Z Day 43 (April 13, 2026). The declaration commits Iran to: (1) immediate cessation of all offensive military operations, (2) no reinstatement of IRGC mine-laying in Hormuz, (3) full compliance with IAEA access under UNSCR 2732, and (4) release of all remaining coalition POWs within 72 hours. The US National Security Council authenticated the document at 21:45Z and President authorized CENTCOM to stand down all offensive operations effective 06:00Z April 13. Israel confirmed acceptance pending IAEA inspection verification. DoD formally notified Congressional leadership.',
    theater: 'Diplomatic',
    confidence: 98,
    source_url: 'https://www.reuters.com/world/middle-east/',
    source_name: 'Reuters / DoD',
    source_type: 'Official',
    verified: true,
    tags: ['ceasefire', 'iran', 'formal-declaration', 'oman', 'day-42', 'centcom', 'effective-d43'],
    author: null,
    created_at: '2026-04-11T21:00:00Z',
  },
  {
    id: 'static-66',
    title: 'NAVCENT: ZB-Alpha 99% Cleared — Full Commercial Hormuz Resumption Imminent',
    summary:
      'NAVCENT issued a maritime advisory on Day 42 declaring ZB-Alpha corridor 99% cleared with full unrestricted commercial transit expected by 12:00Z Day 43. Only one suspected mine location remains in outer Hormuz approach lane and is being investigated by EOD divers; preliminary assessment is that the object is a derelict fishing net marker buoy. USS Chief and USS Gladiator will formally close out the ZB-Alpha MCM tasking upon confirmation. Thirty-one VLCCs have now transited under coalition escort since Day 24. The Islamic Republic of Iran Shipping Lines confirmed all IRISL vessels are returning to pre-conflict routing effective Day 43.',
    theater: 'Hormuz',
    confidence: 96,
    source_url: 'https://www.ukmto.org/',
    source_name: 'UKMTO / NAVCENT',
    source_type: 'Official',
    verified: true,
    tags: ['hormuz', 'zb-alpha', 'mcm', 'clearance', 'day-42', 'ukmto', 'navcent', 'transit'],
    author: null,
    created_at: '2026-04-11T14:00:00Z',
  },
  // ── Day 43 ────────────────────────────────────────────────────────────────
  {
    id: 'static-67',
    title: 'Day 43: Ceasefire Trial Begins 06:00Z — All Coalition Offensive Operations Paused',
    summary:
      'At 06:00Z April 13, 2026 (Day 43), the Abu Dhabi Ceasefire Framework\'s trial ceasefire period entered into effect. CENTCOM Commander issued OPORD 2026-43: all coalition offensive strike operations suspended, DEFCON maintained at 3, full defensive posture including PATRIOT/THAAD batteries on hot standby. No IRGCAF, IRGCN, or IRGC Proxy activity detected across all domains in the first 6 hours. NSC situation room confirmed all-quiet across SIGINT, IMINT, and MASINT domains. Israel Defense Forces separately confirmed IDF compliance. COMPASS ceasefire probability at 95% — maximum model confidence. Pentagon spokesperson: "We are cautiously optimistic. The next 48 hours are critical." All five CENTCOM theaters report compliance.',
    theater: 'Diplomatic',
    confidence: 97,
    source_url: 'https://www.centcom.mil/MEDIA/PRESS-RELEASES/',
    source_name: 'CENTCOM',
    source_type: 'Official',
    verified: true,
    tags: ['ceasefire', 'trial', 'centcom', 'day-43', 'compliance', 'defcon-3', 'opord'],
    author: null,
    created_at: '2026-04-12T06:00:00Z',
  },
  {
    id: 'static-68',
    title: 'First Fully Unrestricted Commercial VLCC Transits Strait of Hormuz Without Mine Escort',
    summary:
      'MT Maran Poseidon (VLCC, Greek flag, fully laden, 2.1 million barrels Basra Light crude) completed a full unrestricted transit of the Strait of Hormuz at 11:42Z Day 43 without mine clearance escort — the first such transit since Day 3 of the conflict. NAVCENT confirmed ZB-Alpha corridor status as 100% clear for the vessel passage. The US 5th Fleet maintained a surface screen at tactical standoff distance as a precautionary measure but did not escort the vessel through the Strait. MarineTraffic AIS confirmed fourteen additional VLCCs transiting or staged to transit within 6 hours. This single transit is estimated to deliver $210 million in crude oil to Asian refineries and signals the effective end of the Hormuz maritime crisis.',
    theater: 'Hormuz',
    confidence: 99,
    source_url: 'https://www.ukmto.org/',
    source_name: 'UKMTO / NAVCENT',
    source_type: 'Official',
    verified: true,
    tags: ['hormuz', 'vlcc', 'transit', 'day-43', 'unrestricted', 'maran-poseidon', 'navcent', 'mcm-complete'],
    author: null,
    created_at: '2026-04-12T11:42:00Z',
  },
  // ── Day 44 ────────────────────────────────────────────────────────────────
  {
    id: 'static-69',
    title: 'POTUS Announces Ceasefire Trial Extended 48 Hours — All Theaters Silent — Iran Compliant',
    summary:
      'President of the United States announced at 14:00Z Day 44 that the Abu Dhabi Ceasefire Framework trial period is extended by 48 hours following full Iranian compliance across all domains in the first 32 hours. No IRGCAF sorties, no IRGCN hostile activity, no ballistic missile warning detections, and no proxy force activity have been recorded since 06:00Z Day 43. The President stated: "Iran has honored its commitments. The shooting has stopped. We are entering the next phase of securing a durable peace." CENTCOM OPORD updated to ceasefire enforcement posture through Day 46 minimum. NSC and Joint Chiefs confirmed the extension is a precursor to formal armistice negotiations. Congressional leadership briefed in the Situation Room.',
    theater: 'Diplomatic',
    confidence: 98,
    source_url: 'https://www.whitehouse.gov/',
    source_name: 'White House',
    source_type: 'Official',
    verified: true,
    tags: ['ceasefire', 'extended', 'potus', 'day-44', 'compliance', 'armistice', 'centcom'],
    author: null,
    created_at: '2026-04-13T14:00:00Z',
  },
  {
    id: 'static-70',
    title: 'ZB-Alpha MCM Mission Complete — Strait of Hormuz 100% Cleared — Full Commercial Traffic Resumed',
    summary:
      'NAVCENT formally declared the ZB-Alpha Mine Countermeasure Operation complete at 09:00Z Day 44. The final suspected mine location was confirmed as a derelict buoy at 07:30Z. USS Chief (MCM-11) and USS Gladiator (MCM-14) have been released from MCM tasking and are returning to 5th Fleet direct support. The Strait of Hormuz is 100% cleared and open to unrestricted commercial maritime traffic for the first time since Day 3. NAVCENT NOTAM: all mine risk warnings for the main Hormuz shipping channel are cancelled. Lloyd\'s of London suspended all Hormuz-specific war-risk premiums at 10:00Z. UKMTO resumed standard transit guidance. MarineTraffic shows 47 vessels transiting or staged within 100nm of Hormuz.',
    theater: 'Hormuz',
    confidence: 99,
    source_url: 'https://www.navcent.navy.mil/',
    source_name: 'NAVCENT',
    source_type: 'Official',
    verified: true,
    tags: ['hormuz', 'zb-alpha', '100-percent', 'mcm-complete', 'day-44', 'ukmto', 'navcent', 'fully-open'],
    author: null,
    created_at: '2026-04-13T09:00:00Z',
  },
  {
    id: 'static-71',
    title: 'IAEA Day 3 Inspection Report: Natanz Centrifuge Halls Confirmed Inoperative — 94% Degradation Validated',
    summary:
      'The IAEA released its Day 3 preliminary inspection report for Natanz FEP on Day 44, confirming the DIA\'s 94% nuclear infrastructure degradation assessment. Key findings: Centrifuge halls A–D all confirmed inoperative; halls A and B are physically collapsed from MOP strikes and are not recoverable without structural rebuild; halls C and D have all cascade interconnects severed and vacuum systems destroyed. Deep sublevel reconnaissance probe reached -72 meters and found no active enrichment equipment. Robotic camera survey confirms no functioning centrifuge cascades. Fordow access team staged in Muscat — inspection entry expected Day 45. IAEA Director General: "Iran\'s enrichment capability as of this inspection date is effectively zero. Reconstitution requires international construction and supply chains — nothing can be hidden from the Agency at this point." Radiological safety status across all assessed sites: GREEN.',
    theater: 'Nuclear',
    confidence: 96,
    source_url: 'https://www.iaea.org/newscenter/focus/iran',
    source_name: 'IAEA',
    source_type: 'Official',
    verified: true,
    tags: ['iaea', 'natanz', 'nuclear', 'bda', 'day-44', '94-percent', 'inspection', 'enrichment-zero'],
    author: 'IAEA Safeguards Dept',
    created_at: '2026-04-13T16:00:00Z',
  },
  {
    id: 'static-72',
    title: 'Brent Crude Settles $82/bbl — GCC Tankers Resume Full Hormuz Routing — CoGH Diversion Cancelled',
    summary:
      'Brent crude oil settled at $81.90 per barrel at Day 44 close, with futures pointing to further normalization toward $75–$78 over 30 days as the ceasefire holds. All major GCC national oil company tanker operators (Saudi Aramco, ADNOC, Kuwait Petroleum, QatarEnergy) have formally cancelled Cape of Good Hope diversion routing effective immediately, reverting to standard Hormuz transit. Saudi Aramco confirmed full CDU-3 and CDU-4 restart at Ras Tanura — export capacity fully restored 20 days after the Day 24 Shahed-136 strike. OPEC+ will meet in two weeks to assess whether emergency production increases should be rolled back as prices normalize. IEA confirmed its emergency stock release program remains available but is expected to not be required. Bloomberg estimates conflict-related supply disruption has cost global consumers $240 billion since Day 3.',
    theater: 'Economic',
    confidence: 97,
    source_url: 'https://www.bloomberg.com/energy',
    source_name: 'Bloomberg',
    source_type: 'Wire',
    verified: true,
    tags: ['oil', 'brent', 'economic', 'hormuz', 'gcc', 'day-44', 'ceasefire', 'aramco', 'cogh-cancelled'],
    author: null,
    created_at: '2026-04-13T20:00:00Z',
  },
]
